### ISSUE TITLE
Sidebar Weirdness

### ISSUE THREAD

**Issue by ericdrgn** [JulienMaille/dribbblish-dynamic-theme#1]
I'll start by saying I am on Linux so I am stuck on the most recent for Linux which is 1.1.56.595 so if that is the problem feel free to close since the readme states 1.1.58. The only reason I am even bothering to ask is because everything else about the theme works perfectly. Basically I can't resize the sidebar all the way to just show icons. Below is a picture of how far it will go. 

![image](https://user-images.githubusercontent.com/60805441/120753666-c4408c80-c4c8-11eb-858b-d2152e398c24.png)

Like I said if this is probably related to my version since linux is behind for whatever reason you can disregard. Buuuuut everything else does work (I just get the unsupported toast message whenever a song changes, but it works regardless) so figured I would ask. My spicetify and the spotify client are both as up to date as allows.

**Comment by JulienMaille** [comment]
I believe this is an issue with Dribbblish, not DribbblishDynamic
