### ISSUE TITLE
A few weird bugs i cant seem to get rid off

### ISSUE THREAD

**Issue by DeadTec9s** [JulienMaille/dribbblish-dynamic-theme#10]
Hi first of all thanks for this theme ive been using it since Christmas or so
recently with the new update when i applied the theme ive had a few graphical bugs that even when i reset wont dissappear. 

One is this faint grey line that occurs on all pages apart from the home page its just above the timeline (shown below) occurs in both dark and light
![image](https://user-images.githubusercontent.com/77972339/122829328-c5eabc80-d2de-11eb-8454-16a624f7369f.png)
![image](https://user-images.githubusercontent.com/77972339/122829607-1cf09180-d2df-11eb-87a7-426e94041bf9.png)

another issue is a mismatch of an overlay on my friends profile pictures
![Picture7](https://user-images.githubusercontent.com/77972339/122829743-4c070300-d2df-11eb-85df-c4564b13b7e2.png)

sorry if the pictures are small or low res i don't know how to get better pictures

i have the text color problem that causes me to not be able to see text in the friends tab when I highlight over it
![Picture8](https://user-images.githubusercontent.com/77972339/122830405-3219f000-d2e0-11eb-9467-1f30e549ca5b.png)

you cant see my cursor but its hovering over the name

also its changed my name in the corner to "new versions 1.4 available"

please help thanks

**Comment by JulienMaille** [comment]
Can you check if these issues are reproducable with the normal, non-dynamic dribblish? For the first one I believe this is the advertisement borders, something I can't do anything about

**Comment by DeadTec9s** [comment]
the mismatched play button to profile picture happens in the standard Dribbblish as well, but the text color problem doesn't
my name is also only changed in the dynamic version

**Comment by JulienMaille** [comment]
I pushed a fix for the text color.
Check your console for errors. The pink color in your screenshot is not normal, you may have not installed the theme properly.
