### ISSUE TITLE
[BUG] Color gets stuck after playing a local file

### ISSUE THREAD

**Issue by Davoleo** [JulienMaille/dribbblish-dynamic-theme#101]
**Describe the bug**
After playing a local file on spotify the color doesn't change anymore according to the track cover
The issue can be bypassed by clicking: Menu > Develop > Reload or by restarting spotify

**To Reproduce**
- Play a normal Spotify track
- Play a local file
- Play a normal Spotify track
- notice the color doesn't change anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/24458276/140663364-bf4def58-4c63-4b02-8ef2-c046e5d98a12.png)

**Desktop Setup**
- OS: Windows v10.0.19043
- Spotify: v1.1.71.560
- Dribbblish: v3.0.1
- Spicetify version: 2.7.2

**Logs**
![image](https://user-images.githubusercontent.com/24458276/140663432-5ad8759c-de1e-429c-81d9-a726caddbd91.png)

**Comment by JulienMaille** [comment]
I believe this is already fixed in the latest version (but not in the 3.0.1 release)
@SendNukez time for new release?

**Comment by SendNukez** [comment]
Yup, go ahead. If you have any questions on how to release let me know. It should all be in [here](https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/83#issuecomment-951917417) and [here](https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/83#issuecomment-953390194) though. Or feel free to create a test release in the test repo if you're unsure.

**Comment by Davoleo** [comment]
ah yeah, can confirm this is fixed on `3.1.0`, thanks for the release, and sorry for the redundant report.

**Comment by SendNukez** [comment]
Np, It wasn't in a release so you couldn't know.
