### ISSUE TITLE
Weird box behind album info

### ISSUE THREAD

**Issue by SendNukez** [JulienMaille/dribbblish-dynamic-theme#103]
Continuation of https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/92#issuecomment-961358650

**Comment by JulienMaille** [comment]
I would suggest testing with latest css remap from https://github.com/khanhas/spicetify-cli/commit/4fa2aca70e8a0cdeafbfb87e83acae7c4223cfb6

**Comment by SendNukez** [comment]
I already tried that, It still looks fine for me. Or maybe I'm doing it wrong. I have to run `spicetify backup apply` so it says `info Fetching remote CSS map for newer compatible tag version: master` correct?

**Comment by JulienMaille** [comment]
Yes that's correct.

**Comment by SendNukez** [comment]
After having installed `Spotify v1.1.72.439` and `Spicetify v2.8.0` I now also have the box. Looks like this is part of the new Spotify update. So I'm guessing this is an css-map issue, since the classes are new.

**Comment by JulienMaille** [comment]
According to spicetify maintainers, this section of the css wasn't mapped before.
