### ISSUE TITLE
New Dark/Bright mode suggestion – Based on Location

### ISSUE THREAD

**Issue by GabWas** [JulienMaille/dribbblish-dynamic-theme#104]
Hey guys, have you thought about adding a new Dark/Bright theme setting that considers the user's location (e.g. latitude)? From what I've got digging through Spicetify issues, getting the current system theme is not working properly (khanhas/spicetify-cli#1095), so that could be a great compromise. I've been using [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) for some time now, and it would be amazing if all the apps changed its theme at once.

**Comment by JulienMaille** [comment]
Do you know that you can set sunset/sunrise time and have auto darkmode based on time?
![image](https://user-images.githubusercontent.com/182520/141656499-731820bf-5cba-4364-88cb-7aa20e9ce173.png)

**Comment by GabWas** [comment]
I was guessing it was a possibility while looking through the code, although for some reason it's not showing up for me.
![Screenshot 2021-11-13 203227](https://user-images.githubusercontent.com/17027711/141657427-44690a26-0eea-4941-b2c3-30705fe5c71b.png)
Still, it would be better if it was done automatically, since sunrise/sunset times do vary.

**Comment by SendNukez** [comment]
Yeah, it not showing up is a known and fixed bug. We just haven't created a new release yet. All in all I think it may be a cool idea, but I don't know if it's that easy to implement since we'd have to handle all kinds of errors and stuff.

**Comment by JulienMaille** [comment]
@SendNukez https://www.npmjs.com/package/sunrise-sunset-js ?

**Comment by SendNukez** [comment]
Could work, I guess we should try to add a "location" input to settings which would show a map using something like [osm](https://www.npmjs.com/package/osm). Inputting the raw coords is fine too, but a map would probably be nicer.

**Comment by JulienMaille** [comment]
I was hoping we could use
```js
navigator.geolocation.getCurrentPosition(function(position) {
  console.log(position.coords);
});
```
but this won't work from Spotify sandbox. If the location can't be retrieve automatically, we'd rather keep it like it is

**Comment by SendNukez** [comment]
By "keep it like it is" you mean not implementing this? Or just use number inputs?

**Comment by JulienMaille** [comment]
Yeah not implementing it, I'm lazy :)

**Comment by JulienMaille** [comment]
@SendNukez we could bring back the "follow system dark mode" feature if Spotify.exe is patched using something like khansas powershell shown here: https://github.com/khanhas/spicetify-cli/issues/1095#issuecomment-980473116
Now we need a way to make it easy for users

**Comment by SendNukez** [comment]
This would have to be run every time Spotify is updated though if I understand correctly. It also could cause problems with Antivirus software since it is modifying the exe no?

**Comment by JulienMaille** [comment]
Lets continue on #127
