### ISSUE TITLE
missing settings for start/stop dates for "based on time" dark mode

### ISSUE THREAD

**Issue by JulienMaille** [JulienMaille/dribbblish-dynamic-theme#107]
**Screenshots**
![image](https://user-images.githubusercontent.com/182520/141344458-b4384ac8-1d6f-4a35-b78e-d71568b52459.png)

**Desktop Setup**
- OS: Windows v10.0.22000
- Spotify: v1.1.72.439
- Spicetify: v2.8.0
- Dribbblish: v3.1.1-6f7096b

**Comment by SendNukez** [comment]
Oh, i forgot to change https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/19aeb86204f1166aaf06bd8530ee37b1a99def01/src/js/main.js#L548 to `val == "time"` after changing the way select inputs are handled. 🤦‍♂️

**Comment by SendNukez** [comment]
And now I have managed to accidentally push all my local changes instead of only the fix. Today is really not my day...

**Comment by JulienMaille** [comment]
We all make mistakes, don't worry.
