### ISSUE TITLE
Double update prompt

### ISSUE THREAD

**Issue by shifting-tides** [JulienMaille/dribbblish-dynamic-theme#108]
As you can see, Dribbblish doubles the very same update prompt
![image](https://user-images.githubusercontent.com/63145386/141412488-120e3606-030e-4188-a1c3-f873808d2c03.png)
![image](https://user-images.githubusercontent.com/63145386/141412727-9e267a3b-d900-4e21-bd60-08cef64d1c5e.png)

**Comment by SendNukez** [comment]
I'm currently working on redesigning the whole user-icon situation so we don't need to add the update button to the context menu and instead show a update button next to the user's profile picture. I got the idea when trying to fix this. Thank you for bringing this up!

**Comment by SendNukez** [comment]
I have updated it to use this new method it looks like this:
![image](https://user-images.githubusercontent.com/29760988/141505195-5274266c-f744-487c-aed8-ae1b58f41ec9.png)
(the `</>` icon is just present when you use a dev-build)
