### ISSUE TITLE
Stuck in Pink Theme

### ISSUE THREAD

**Issue by gabrielmaster123** [JulienMaille/dribbblish-dynamic-theme#11]
I always have this theme and I cant do anything about it it doesnt change
![image](https://user-images.githubusercontent.com/60442371/123124665-28130100-d448-11eb-811b-da71cedfa87c.png)

**Comment by JulienMaille** [comment]
check your logs, you must have failed to install spicetify/this theme

**Comment by gabrielmaster123** [comment]
Do I just reinstall spicetify and spotify?

**Comment by JulienMaille** [comment]
Try to upgrade spicetify

**Comment by gabrielmaster123** [comment]
I was on newest version but then I just reinstalled everything now it works
