### ISSUE TITLE
'Add to playlist' context menu scrolling broken

### ISSUE THREAD

**Issue by rkeeley** [JulienMaille/dribbblish-dynamic-theme#114]
**Describe the bug**
Scrolling functionality in the `Add to playlist` context menu is missing or broken. Menu items can still be accessed with the arrow keys, but off-screen folders won't be visibly opened.

**To Reproduce**
1. Have enough playlists to require more space in the Add to playlist context menu than you have screen height
2. Right-click a song, `Add to playlist`, attempt to scroll down to the playlists at the bottom of the menu

I tried this without the Dribbblish theme/extension and it still works as expected.

**Screenshots**
![](https://i.imgur.com/9Zc3gLt.png)

You can see in the left sidebar that I have more playlists and folders below those in the context menu, but they're inaccessible (by mouse).

![](https://i.imgur.com/y4C2RFW.png)

The menu items are still accessible with the arrow keys. Because this folder is still technically on the screen, the menu for it is opened in this screenshot, but the ones at the bottom of the menu would only be opened invisibly.

Adding `overflow: auto` to the containing `data-tippy-root` div's `style` re-enabled scrolling, but the menu's visible background and borders then scrolled too. I wanted to try changing the `position`, but it resets whenever the context menu comes into focus, and I don't know enough to know where to go from here. 

**Logs**

```console
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621881)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624465)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859683)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883415)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096998)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829219)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883194)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868073)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866995)
c @ vendor~xpui.js:29
2TypeError: Cannot read properties of null (reading 'text')
    at Info.set (Info.js:57)
    at main.js:843
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/367.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19042`
Spotify: `v1.1.72.439`
Spicetify: `v2.8.1`
Dribbblish: `v4.0.0-8ba60b4`

**Extensions**
- autoSkipVideo.js
- shuffle+.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.0.0",
    "openSettingsInfo": true,
    "rightBigCover": true,
    "roundSidebarIcons": false,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 0,
    "sidebarGapRight": 23,
    "fadeDuration": 0.5,
    "colorSelectionAlgorithm": "vibrant",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "time",
    "darkModeOnTime": "18:15",
    "darkModeOffTime": "07:00",
    "playbarShadow": false,
    "winTopBar": "none",
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": false,
    "hideAds": false
}
```

**Comment by JulienMaille** [comment]
Do you have the same issue with original dribbblish theme?

**Comment by rkeeley** [comment]
Nope, context menu scrolling works with `current_theme = Dribbblish`, even if I leave `dribbblish-dynamic.js` in the `extensions` list. 

With `Dribbblish` as the theme and without `dribbblish-dynamic.js` in the extensions list:

![image](https://user-images.githubusercontent.com/6667616/142515861-9c808fee-38da-4cc6-b521-5e1fca0bc80b.png)

With `Dribbblish` as the theme and `dribbblish-dynamic.js` in the extensions list (weird screenshot because the Dribbblish Settings menu is stuck open and I can only get to a track context menu from the expanded cover image):

![image](https://user-images.githubusercontent.com/6667616/142515037-7dc62977-e3ed-481d-90e3-d38f6aff70c5.png)

This isn't a huge issue since I can work around the problem by dragging and dropping tracks into playlists via the sidebar, but I figured it was worth mentioning since it seems to be a regression.

**Comment by JulienMaille** [comment]
Ok so the problem is clearly created from these 2 lines
![image](https://user-images.githubusercontent.com/182520/142696863-45ec86b3-c6f6-404f-9250-15ca458a5256.png)
https://github.com/JulienMaille/dribbblish-dynamic-theme/blame/c2d7f851b1fff62377394ae2b6e9586964be9d68/src/styles/ContextMenu.scss#L3-L4
