### ISSUE TITLE
Theme settings bar gets cut in half

### ISSUE THREAD

**Issue by rcompier** [JulienMaille/dribbblish-dynamic-theme#115]
**Describe the bug**
In the Dribbblish setting under 'Theme' the color bar on the left gets cut in half if you put 'Color Selection Mode' on 'Default' while if you put it on 'Luminance' it covers the whole div

**To Reproduce**
- Go to Dribbbling settings
- Expand the 'Theme' section
- Change the 'Color Selection mode'

![image](https://user-images.githubusercontent.com/21107109/142378974-b43a6150-4fca-481f-a4de-7c02965f3855.png)

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19043`
Spotify: `v1.1.72.439`
Spicetify: `v2.8.1`
Dribbblish: `v4.0.0-8ba60b4`

**Extensions**
- shuffle+.js
- fullAppDisplay.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.0.0",
    "openSettingsInfo": true,
    "rightBigCover": true,
    "roundSidebarIcons": true,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "fadeDuration": 0.5,
    "colorSelectionAlgorithm": "vibrant",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "playbarShadow": false,
    "winTopBar": "none-padding",
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": false
}
```

**Comment by SendNukez** [comment]
This is intended behavior, the bar shows on settings that have been changed from default
