### ISSUE TITLE
background album art is cut off

### ISSUE THREAD

**Issue by Lseoksee** [JulienMaille/dribbblish-dynamic-theme#116]
**Describe the bug**
background album art is cut off 

**To Reproduce**
Start Spotify

**Screenshots**
![Screenshot 2021-11-18 18-36-47](https://user-images.githubusercontent.com/91320047/142390156-4653ad70-c5b1-485a-9183-f2d56db78b71.png)

**Desktop Setup**
 - Operating System: Windows 11
 - Spotify version: 1.1.72.439
 - Spicetify version: 2.8.1
 - Dribbblish version  4.0.0

**Comment by SendNukez** [comment]
This is a lyrics-plus problem, you have to disable the background in the lyrics-plus settings

**Comment by Lseoksee** [comment]
> This is a lyrics-plus problem, you have to disable the background in the lyrics-plus settings

It's hard to see, so I took a picture of the lyrics plus window, and no matter what window I go in, the album art is cut off.

-old Dribbblish version (3.0.1)

![Screenshot 2021-11-19 01-15-07](https://user-images.githubusercontent.com/91320047/142454815-583b87ce-ce77-4028-a4e5-dc0df16dcdf6.png)

new Dribbblish version (4.0.0)

![Screenshot 2021-11-19 01-10-31](https://user-images.githubusercontent.com/91320047/142454931-01bed65e-77ff-48f8-88ea-03c47b40eec9.png)

**Comment by SendNukez** [comment]
This slipped by me since it only happened when friends activity is disabled
