### ISSUE TITLE
Situational colour clash on some elements

### ISSUE THREAD

**Issue by Jordy3D** [JulienMaille/dribbblish-dynamic-theme#117]
Basically title. Colours gained from album covers and the like can end up clashing with existing Spotify elements, as seen here. 
![image](https://user-images.githubusercontent.com/19144524/142757830-dc7ace67-1329-48c6-98db-ccb16750e1f9.png)
An option to disable/override text colour changes would likely go a long way to fix the issue, leaving them as default or manually setting a colour with a toggle or something.

**Comment by JulienMaille** [comment]
I've noticed that too but I believe the issue comes from the css mapping from Spicetify.

**Comment by JulienMaille** [comment]
Should be fixed by https://github.com/khanhas/spicetify-cli/pull/1310
