### ISSUE TITLE
Song Progress Bar CPU utilization

### ISSUE THREAD

**Issue by rkeeley** [JulienMaille/dribbblish-dynamic-theme#118]
**Describe the bug**
When the desktop app is visible, the DribbblishDynamic theme's progress bar update code causes 10 times the amount of CPU utilization when compared to non-DribbblishDynamic themes. On my computer Spotify goes from less than 4% normally to up to 35% when music is playing and the app is visible. 

This doesn't happen when the music is paused or when the app is minimized. It also happens when music is playing on another device and the progress is being watched on the desktop app. It doesn't happen with other themes, even when `dribbblish-dynamic.js` is in the extensions list.

It does happen when `current_theme = DribbblishDynamic` and `dribbblish-dynamic.js` isn't in the extensions list, but to a lesser degree: about 5x utilization increase compared to 10x. The progress bar doesn't show up (for me) with this configuration, so maybe the difference is the lack of UI update code to be run.

I've been looking through the code (mainly [this function](https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/main/src/js/main.js#L227)) and DevTools performance reports to see if I can fix this myself, but I figured I would report it in the meantime in case somebody with more knowledge has a solution. I assume this isn't something that shouldn't be chalked up to Javascript performance since it doesn't happen with other themes or in the vanilla desktop app.

**To Reproduce**
1. Open Task Manager. Note CPU utilization for Spotify.
2. Play music on Spotify. Note difference in CPU utilization.

**Screenshots**
![image](https://user-images.githubusercontent.com/6667616/142790203-d952de14-38e0-438e-966e-b305be0682fb.png)

Resource Monitor stats while the problem is occurring and the desktop app is visible. The dip in the middle is when the music is paused. The rest is when it's playing.

**Logs**

```console
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621881)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624465)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859683)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883415)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096998)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829219)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883194)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868073)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866995)
c @ vendor~xpui.js:29
2TypeError: Cannot read properties of null (reading 'text')
    at Info.set (Info.js:57)
    at main.js:843
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/106.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/376.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19042`
Spotify: `v1.1.72.439`
Spicetify: `v2.8.1`
Dribbblish: `v4.0.0-8ba60b4`

**Extensions**
- autoSkipVideo.js
- shuffle+.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.0.0",
    "openSettingsInfo": true,
    "rightBigCover": true,
    "roundSidebarIcons": false,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 0,
    "sidebarGapRight": 23,
    "fadeDuration": 0.5,
    "colorSelectionAlgorithm": "vibrant",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "time",
    "darkModeOnTime": "18:15",
    "darkModeOffTime": "07:00",
    "playbarShadow": false,
    "winTopBar": "none",
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": false,
    "hideAds": false
}
```

**Comment by rkeeley** [comment]
This is another one of those "would be nice if it wasn't this way" kind of bugs since I can just minimize the app to avoid the problem, but then I don't get to enjoy this awesome theme that I'm glad exists. I only noticed it because it was making me lag while playing games. I've learned a bit about js and webpack while debugging this, so thanks for giving me a reason to learn 🙂

**Comment by JulienMaille** [comment]
Thanks for your report. The progress bar has its transition animated with css. Have you tried toggling off this rule and see if you get any improvement?

**Comment by rkeeley** [comment]
Yeah, that's a major improvement!

![image](https://user-images.githubusercontent.com/6667616/142988528-843d12f6-1256-469e-a0d2-a8b4ad6608d4.png)

This screenshot was taken while running the current release. The bump in the beginning was a song change. The valley is pretty much my idle utilization with Spotify playing. after turning off the progress-bar display with 

```javascript
document.querySelectorAll('.progress-bar').forEach((pb) => { pb.style.display = 'none'; })
```

Running a dev version of the theme with the lines you posted commented out had similar results. This is what a song change looks like without any manual DevTools intervention:

![image](https://user-images.githubusercontent.com/6667616/142989171-de0e1722-591e-4aa7-9193-696209b33874.png)

I figured the problem was the div's `style` being updated too often, but I wasn't really sure what to do about it. I'm using an Intel i5-6600K and an Nvidia 980 Ti for reference, and Hardware Acceleration is enabled in Spotify.

Thanks for another quick response and workaround 🙂

**Comment by JulienMaille** [comment]
@SendNukez are you ok to remove the transition on `left` attribute? It's computer intensive and it looks weird imho.

**Comment by SendNukez** [comment]
I have added an option to disable the transition since I don't really notice any major performance issues using it. You can test it by using / installing [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/actions/runs/1496389404) zip.
