### ISSUE TITLE
An option to disable playlists images on sidebar

### ISSUE THREAD

**Issue by ArthRMH** [JulienMaille/dribbblish-dynamic-theme#119]
Dunno, but when the app asked for me to update it for some reeson it disabled the playlist image view on the sidebar, and the application became much faster, so i think it's that what's making it slow, at least on my pc. Can you make an option to disable it please? (Ps: the same thing happen on Windows and Linux)

![image](https://user-images.githubusercontent.com/86346283/143156241-563b9c3c-d254-411e-8241-d224225f0682.png)

**Comment by ArthRMH** [comment]
wait, the playlists images came back and the app didn't slow down, so i don't know what's causing this, i'll be here if you guys need any log or something 
![image](https://user-images.githubusercontent.com/86346283/143176990-d09770a0-58f0-4795-85db-f1ae107564fe.png)

**Comment by alixti** [comment]
I updated Spicetify with the "upgrade" command and the issue got fixed for me.
