### ISSUE TITLE
Background color and playlist icon issue

### ISSUE THREAD

**Issue by hennaceur** [JulienMaille/dribbblish-dynamic-theme#12]
**Describe the bug**
Starting Spotify with dynamic dribbblish has a weird issue where the all the icons are transparent and background is white until I skip to the next song which makes it work properly after. But, after updating to the newest Spicetify 2.3.0, all playlist icons are not showing anymore.

**To Reproduce**
Starting application

**Screenshots**
`after starting Spotify`
![image](https://user-images.githubusercontent.com/60199730/123140958-70272900-d432-11eb-9510-49679a4a2bc0.png)

`after skipping to next song`
![image](https://user-images.githubusercontent.com/60199730/123141272-ca27ee80-d432-11eb-879b-fb4596f78127.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

```console
dribbblish-dynamic.js:163 Mixed Content: The page at 'https://xpui.app.spotify.com/index.html' was loaded over HTTPS, but requested an insecure element 'http://local_resource_host/dribbblish.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(anonymous) @ dribbblish-dynamic.js:163
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
spicetifyWrapper.js:875 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:875
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2669761)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2672043)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2104264
    at Ia (https://xpui.app.spotify.com/vendor~xpui.js:29:2947909)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2971761)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3164306)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2917417)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2971540)
    at Ts (https://xpui.app.spotify.com/vendor~xpui.js:29:2956311)
    at ys (https://xpui.app.spotify.com/vendor~xpui.js:29:2955233)
c @ vendor~xpui.js:29
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
The FetchEvent for "https://xpui.app.spotify.com/popupLyrics.js" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://xpui.app.spotify.com/popupLyrics.js","error":{}}]
    at D._handle (https://xpui.app.spotify.com/service-worker.js:1:20548)
    at async D._getResponse (https://xpui.app.spotify.com/service-worker.js:1:10318)
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
popupLyrics.js:1 Failed to load resource: net::ERR_FAILED
2vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
dribbblish.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
RobotoMedium.woff2:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
GoogleSansDisplayRegular.woff2:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
Roboto.woff2:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
5vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
GoogleSansDisplayMedium.woff2:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/808.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-routes-artist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by HybridRaven** [comment]
Same here.... no playlist icons.... 

Win10 21H1

**Comment by JulienMaille** [comment]
Do you have the same issue with the original Dribbling theme?

**Comment by gabrielmaster123** [comment]
No Playlist icons here. Did you find a solution yet?

**Comment by doongs** [comment]
I installed the theme on my desktop this Tuesday 6/22 and everything worked absolutely perfectly. Sidebar pictures all loaded correctly, and the custom folder images worked fine. I installed the theme on my laptop tonight and had the above issues. I copied all of my Spicetify files from my desktop to my laptop and everything works perfectly fine now. 

If there's an issue, it's with something that was added in the last two days. I can share my Spicetify directory if you need itit.

**Comment by JulienMaille** [comment]
can you share both directories so I can diff them?

**Comment by doongs** [comment]
The files are too big to share via a message here, so you can grab them off of my [Google Drive](https://drive.google.com/file/d/1Mqb7UuSJybSnW6ftL18iUa2hte-q4lzK/view?usp=sharing).

**Comment by bakzkndd** [comment]
![image](https://user-images.githubusercontent.com/50497725/123481106-93ed9900-d603-11eb-8b23-31fc48d8f120.png)
got these errors in the console and the same issue (everything updated to most recent builds)

**Comment by JulienMaille** [comment]
Take a shot at latest update

**Comment by bakzkndd** [comment]
![image](https://user-images.githubusercontent.com/50497725/123488061-7b837b80-d60f-11eb-8989-d3805bc41505.png)
hovering basically makes text impossible to see (tho not that big a deal) and the playlist covers are still missing for me

**Comment by JulienMaille** [comment]
hover color fixed in latest commit, playlist icons work fine here

**Comment by doongs** [comment]
Maybe I don't have a totally clean install, but I just tried to update to the latest commit. First by using the PowerShell commands, and then secondly by just putting the new files into place manually. 

This is what I'm getting:
![image](https://user-images.githubusercontent.com/61425162/123491530-e5d2f680-d5e4-11eb-86f9-9077428213e7.png)

Tried to try a few troubleshooting steps to make sure that I wasn't doing something wrong on my end, but I just ended up manually putting in my good files from earlier.

**Comment by JulienMaille** [comment]
Which version of Spicetify are you running? Try to update it

**Comment by ps13g** [comment]
> Maybe I don't have a totally clean install, but I just tried to update to the latest commit. First by using the PowerShell commands, and then secondly by just putting the new files into place manually.
> 
> This is what I'm getting:
> ![image](https://user-images.githubusercontent.com/61425162/123491530-e5d2f680-d5e4-11eb-86f9-9077428213e7.png)
> 
> Tried to try a few troubleshooting steps to make sure that I wasn't doing something wrong on my end, but I just ended up manually putting in my good files from earlier.

Ok so this same issue occurred to me yesterday on MacOS and so what you need to do is upgrade Spicetify to the latest version (2.5.0) and then go into the spicetify data remove the dribblish.js and dribbblish-dynamic.js manually and then use these commands in powershell spicetify config extensions dribbblish.js- spicetify config extensions dribbblish-dynamic.js- 
spicetify apply and then download the code from the github manually as a zip and then do the normal commands that you would do to apply dribbblish

**Comment by danielphan2003** [comment]
Can confirm the latest commit ([`71e2b01`](https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/71e2b01fc2733cac0cedc8744574c37f64994882))  works for me with spicetify-cli v2.5.0 on Spotify v1.1.56.
