### ISSUE TITLE
Frozen on one screen, can't do anything at all on spotify

### ISSUE THREAD

**Issue by disc-abdul0001** [JulienMaille/dribbblish-dynamic-theme#120]
**Describe the bug**
Frozen on one screen. Can't click anything at all. Have reinstalled spicetify, spotify, dribbblish to no avail.
**To Reproduce**
Occured first when setting a custom colour for my spotify theme in the dribbblish settings
**Screenshots**
![What it looks like ](https://user-images.githubusercontent.com/95005810/143365996-9ab72735-082a-4352-834b-9e4418a3f9fc.png)

**Desktop Setup**
 - Operating System: [e.g. Windows 10, MacOS 10.14] **Windows 10**
 - Spotify version [e.g. 1.1.71.560] from `Menu (Three dots top left) > Help > About` **2.8.2**
 - Spicetify version [e.g. 2.4.1] run `spicetify -v`  **2.8.2**
 - Dribbblish version [e.g. 3.0.1] from `Dribblish Settings > About` **Can't check in Spotify app, but I installed 4.0.0**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Shows nothing in console at all.**

**Comment by disc-abdul0001** [comment]
1. C:\Users\owner.spicetify\Themes\DribbblishDynamic https://prnt.sc/20u3nqo
2. C:\Users\owner.spicetify\Extensions https://prnt.sc/20u3ol9
3. Config: 
[Patch]

[Setting]
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
current_theme           = DribbblishDynamic
prefs_path              = C:\Users\owner\AppData\Roaming\Spotify\prefs
color_scheme            = base
inject_css              = 1
overwrite_assets        = 1
spotify_path            = C:\Users\owner\AppData\Roaming\Spotify

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features = 1
extensions            = dribbblish-dynamic.js|fullScreen.js|playNext.js
custom_apps           = spicetify-marketplace|lyrics-plus
sidebar_config        = 1
home_config           = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.72.439.gc253025e
with    = 2.8.2

**Comment by JulienMaille** [comment]
Have you installed the theme using the powershell script? Can you fix it bu removing dribbblish?

**Comment by disc-abdul0001** [comment]
> Have you installed the theme using the powershell script? Can you fix it bu removing dribbblish?

I installed it manually, then uninstalled it, then installed it with powershell trying to fix it but it gave the same result. Yes, spotify goes back to normal and works with other extensions once I remove  both the dribbblish theme and extension.

**Comment by JulienMaille** [comment]
Can you try to update spicetify with the one just released?

**Comment by disc-abdul0001** [comment]
>Can you try to update spicetify with the one just released? Please double check the Spotify version you reported, it is incorrect.

Updated spicetify, no difference 
1.1.72.439.gc253025e

**Comment by disc-abdul0001** [comment]
**FIXED**
I installed the Dribbblish theme through the Spicetify marketplace then added the plugin afterwards. Ty for the help!
