### ISSUE TITLE
No color selection

### ISSUE THREAD

**Issue by queeenn** [JulienMaille/dribbblish-dynamic-theme#121]
**Describe the bug**
**I do not have color selection**
**To Reproduce**
**Install theme from marketplace then install the extension**
**Screenshots**
![image](https://user-images.githubusercontent.com/37917759/143401566-625d791a-a93f-4524-a18e-1d240570d8c6.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19043`
Spotify: `v1.1.73.515`
Spicetify: `v2.8.2`
Dribbblish: `v4.0.0-8ba60b4`

**Extensions**
- fullScreen.js
- playNext.js
- shuffle+
- loopyLoop
- trashbin
- bookmark
- dribbblish-dynamic.js
- extension.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.0.0",
    "openSettingsInfo": true,
    "rightBigCover": true,
    "roundSidebarIcons": true,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "fadeDuration": 0.9,
    "playbarShadow": true,
    "winTopBar": "none",
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": true
}
```

**Comment by JulienMaille** [comment]
Have you pressed the down arrows next to each settings' subsection?

**Comment by queeenn** [comment]
> Have you pressed the down arrows next to each settings' subsection?

Yes I just collapsed them to show all the settings I have

**Comment by JulienMaille** [comment]
Unfold the `Animation & Theme` and if you still can't find it reopen this with a snapshot
