### ISSUE TITLE
Playlist List not allowing me to scroll down to all of them

### ISSUE THREAD

**Issue by AlexMassin** [JulienMaille/dribbblish-dynamic-theme#123]
**Describe the bug**

The list of playlists on the sidebar does not allow me to scroll past a certain point even though I have playlists under.    

    **To Reproduce**
Have more than 15 playlists.
    
    **Screenshots**
    
![image](https://user-images.githubusercontent.com/22510297/143668453-8bfd345a-1885-429a-9e36-d014e17cc733.png)

    **Logs**
    Add logs from console. To do that
    1. Run `spicetify enable-devtool` in terminal
    2. Spotify will be restarted
    3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
    4. Navigate to tab Console
    5. Copy console window content.
    
    ```console
    (Please paste here console logs or attach a screenshot)
    ```
    
    ---
    
    ### Info for Contributors:
    
    **Versions**
    OS: `Windows v10.0.18363`
Spotify: `v1.1.73.517`
Spicetify: `v2.8.3`
Dribbblish: `vDev-af5af92`
    
    **Extensions**
    - extension.js
    
    **Settings**
    ```json
    {
    "EXPORTED_WITH": "Dev",
    "showLoadingScreen": true,
    "openSettingsInfo": true,
    "showSearchBox": false,
    "rightBigCover": true,
    "roundSidebarIcons": false,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 0,
    "sidebarGapRight": 15,
    "winTopBar": "none",
    "playbarShadow": true,
    "playbarTransition": true,
    "playerControlsStyle": "spotify",
    "showAlbumInfoInPlaybar": true,
    "hideAds": false,
    "fadeDuration": 1.5,
    "colorSelectionAlgorithm": "vibrant",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "luminance",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00"
}
    ```

**Comment by JulienMaille** [comment]
Please check if this works for you: https://github.com/JulienMaille/dribbblish-dynamic-theme/pull/89/files

**Comment by AlexMassin** [comment]
> Please check if this works for you: https://github.com/JulienMaille/dribbblish-dynamic-theme/pull/89/files

Do you know if I can do this if I've installed using the marketplace extension? I can't seem to find where they save the files to locally change them.

**Comment by SendNukez** [comment]
Yes, you still have to do this. The marketplace only adds links to the theme's files, it does not change the config.
