### ISSUE TITLE
A feature I think that could be added

### ISSUE THREAD

**Issue by Ablymora** [JulienMaille/dribbblish-dynamic-theme#126]
**Is your feature request related to a problem? Please describe.**

I really like the new dribbblishdynamic look, however my preference is more on the normal dribbblish look
but with the new features of the latest dynamic

**Describe the solution you'd like**

I think that an option of enabling or disabling the background transition would work for this.
The static option still changes colors when I change music so I think that could also be changed.

**Describe alternatives you've considered**

I could use normal dribbblish however I don't think it is at the latest update yet. (If it is please just reply and tell me)

**Additional context**

**Comment by SendNukez** [comment]
You can use the `Custom CSS` option in the latest (not released yet) build. Something like:
```css
.Root__top-container::before { display: none; }
```
Should work. If you'd like to give it a try you can download [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/suites/4489328469/artifacts/119624059) and follow the [Manual Install](https://github.com/JulienMaille/dribbblish-dynamic-theme#manual-install) steps using this build.
