### ISSUE TITLE
Switch theme based on system theme.

### ISSUE THREAD

**Issue by evanbrierton** [JulienMaille/dribbblish-dynamic-theme#127]
Would be cool if there was an option so that the theme could match the system theme on macOS and/or Windows rather than just switching based on time of day.

This could be achieved using the [prefers-color-scheme media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

Or perhaps [Window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) if the theme switching should be handled primarily in JS.

**Comment by evanbrierton** [comment]
Something along the lines of this may work.

```js
function checkDarkLightMode() {
    const theme = Dribbblish.config.get("theme");
    if (theme == "time") {
        const start = 60 * parseInt(Dribbblish.config.get("darkModeOnTime").split(":")[0]) + parseInt(Dribbblish.config.get("darkModeOnTime").split(":")[1]);
        const end = 60 * parseInt(Dribbblish.config.get("darkModeOffTime").split(":")[0]) + parseInt(Dribbblish.config.get("darkModeOffTime").split(":")[1]);

        const now = new Date();
        const time = 60 * now.getHours() + now.getMinutes();

        let dark;
        if (end < start) dark = start <= time || time < end;
        else dark = start <= time && time < end;
        toggleDark(dark);
    }
    if (theme === "system") {
	toggleDark(window.matchMedia('(prefers-color-scheme: dark)').matches);
    }
}
```

**Comment by SendNukez** [comment]
I'm pretty sure this does not currently work https://github.com/khanhas/spicetify-cli/issues/1095. The last time I tried it still didn't work is it working for you?

**Comment by evanbrierton** [comment]
Yes it's working for me currently, my system info is:
OS: Osx v12.0.1
Spotify: v1.1.73.517
Spicetify: v2.8.3
Dribbblish: v4.0.0-8ba60b4

**Comment by evanbrierton** [comment]
I've published a demo of it working on my system [here](https://www.youtube.com/watch?v=li3P-4TwvwU)

**Comment by evanbrierton** [comment]
The full implementation is in PR #128

**Comment by JulienMaille** [comment]
Thank you. Would be nice to collect feedback from Linux users.
