### ISSUE TITLE
Color staying the same after song change

### ISSUE THREAD

**Issue by Trixfinity** [JulienMaille/dribbblish-dynamic-theme#13]
Basically the color stays the same after a few songs where it just stays at one song
![image](https://user-images.githubusercontent.com/41873350/124338776-4c20c180-db6f-11eb-94cf-55537e148cfa.png)
![image](https://user-images.githubusercontent.com/41873350/124338784-55aa2980-db6f-11eb-8c6c-c1fcbb552607.png)
Then I restart Spotify and it resets

![image](https://user-images.githubusercontent.com/41873350/124338799-71adcb00-db6f-11eb-8b21-989b95760fd9.png)
![image](https://user-images.githubusercontent.com/41873350/124338805-76727f00-db6f-11eb-97a0-336a04e7a133.png)
![image](https://user-images.githubusercontent.com/41873350/124338811-7bcfc980-db6f-11eb-8946-49d1add0a561.png)

**Comment by h-marti** [comment]
Same issue with the colors on my Windows 10 (20H1)

- Spotify version: 1.1.62.583
- Spicetify version: 2.5.0

**Comment by JulienMaille** [comment]
i can't help without logs

**Comment by Trixfinity** [comment]
How do I get the logs?

**Comment by Trixfinity** [comment]
> I can't help without logs
![image](https://user-images.githubusercontent.com/41873350/124321249-ff26f600-db42-11eb-82f2-116cab3888b8.png)
it shows the last two repeating constantly

**Comment by Trixfinity** [comment]
Sorry, I used the PowerShell download link and everything worked out, so thanks for making the theme work for Spicetify V2!

**Comment by Trixfinity** [comment]
Sorry, I just got the same issue [h-marti](https://github.com/h-marti) got where the color just stops changing after a certain period of time.

**Comment by JulienMaille** [comment]
@Trixfinity @Trixfinity the color change seems to stop whenever an advertisement is played. Can you reproduce this and share your console logs?

**Comment by Trixfinity** [comment]
@JulienMaille 
![image](https://user-images.githubusercontent.com/41873350/125138666-a8866280-e0d4-11eb-85ae-c8e83d27a4f6.png)
![image](https://user-images.githubusercontent.com/41873350/125138678-b0de9d80-e0d4-11eb-94d6-941280a6fbaf.png)
