### ISSUE TITLE
The theme is broken !

### ISSUE THREAD

**Issue by HazemDa1st** [JulienMaille/dribbblish-dynamic-theme#130]
**Describe the bug**
 -Everting was working perfectly and then it's broken out the blue. I uninstalled everything (spotify+spicetify) then reinstall and it worked again for few hours ,then Spotify freezed and I had to close in the task manager but when I opened it , I found it broken again.   
**To Reproduce**

**Screenshots**

![Screenshot 2021-11-30 221947](https://user-images.githubusercontent.com/47460655/144121818-f809f53c-0e25-4ff8-a699-301ce7eff5f3.png)

**Desktop Setup**
- Operating System: windows 11 
- Spotify: < 1.73
- Spicetify: <2.8.3
- Dribbblish: <4.0

**Logs**

   I opened the console and it's empty !!

funny thing , spotify responds to media keys strokes although everything looks broken as in the screenshot.

**Comment by JulienMaille** [comment]
Can you try latest code from here?
[DribbblishDynamic_vDev-193953d.zip](https://github.com/JulienMaille/dribbblish-dynamic-theme/files/7628996/DribbblishDynamic_vDev-193953d.zip)

**Comment by HazemDa1st** [comment]
I ended up rolling back to Spotify 1.72 , things works fine for now so I wouldn't be able to tell if your solution works or not .
