### ISSUE TITLE
sponsor ads is not getting remove when you toggle on no ads

### ISSUE THREAD

**Issue by JackPlaysGames0510** [JulienMaille/dribbblish-dynamic-theme#132]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19043`
Spotify: `v1.1.73.517`
Spicetify: `v2.8.3`
Dribbblish: `v4.0.0-8ba60b4`

**Extensions**
- autoSkipExplicit.js
- autoSkipVideo.js
- bookmark.js
- fullAppDisplay.js
- keyboardShortcut.js
- loopyLoop.js
- popupLyrics.js
- shuffle+.js
- trashbin.js
- webnowplaying.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.0.0",
    "openSettingsInfo": true,
    "rightBigCover": true,
    "roundSidebarIcons": true,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "fadeDuration": 0.5,
    "colorSelectionAlgorithm": "colorthief",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "playbarShadow": true,
    "winTopBar": "none-padding",
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": true
}
```

**Comment by SendNukez** [comment]
See [this](https://github.com/Daksh777/SpotifyNoPremium/issues/23)
