### ISSUE TITLE
Batch file for a quicker update.

### ISSUE THREAD

**Issue by alixti** [JulienMaille/dribbblish-dynamic-theme#135]
**Is your feature request related to a problem? Please describe.**
When Spotify updates all the modifications through Spicetify are removed and I have to copy and paste the command on powershell everytime this happens.

**Describe the solution you'd like**
Like the title says, create a batch file to just open it and execute the command. It would be nice that it is included on the repository so other people can use it too and make the process easier.

**Describe alternatives you've considered**
I don't know by Mac or Linux but this is what I've done in Windows so far:
```
@echo off
title Dribbblish Dynamic Updater
spicetify clear
spicetify upgrade
powershell -Command "& {Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/JulienMaille/dribbblish-dynamic-theme/master/install.ps1" | Invoke-Expression}"
pause
exit
```
(It would be nice to see a warning like "You should use this only if Spotify has updated, do you want to update (Y/N)?" but this is just an idea)

**Comment by alixti** [comment]
Also another idea is to ask if the theme works correctly if not execute the command `spicetify restore backup`.

**Comment by alixti** [comment]
Something like this:

```
@echo off
title Dribbblish Dynamic Updater

:MainUpdate
echo Clearing old backup...
spicetify clear
echo Checking if new version of Spicetify is available.
spicetify upgrade
echo Installing theme...
powershell -Command "& {Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/JulienMaille/dribbblish-dynamic-theme/master/install.ps1" | Invoke-Expression}"

:AskIfThemeWorksCorrectly
echo Does the theme works correctly? (Y/N)
set INPUT=
set /P INPUT=Answer: %=%
If /I "%INPUT%"=="y" goto AskIfThemeWorksCorrectlyTrue
If /I "%INPUT%"=="n" goto AskIfThemeWorksCorrectlyFalse
goto AskIfThemeWorksCorrectly

:AskIfThemeWorksCorrectlyTrue
exit

:AskIfThemeWorksCorrectlyFalse
echo Restoring backup...
spicetify restore backup
pause
```

**Comment by JulienMaille** [comment]
I don't get it. You shouldn't have to reinstall the theme after a Spotify update.

**Comment by alixti** [comment]
> I don't get it. You shouldn't have to reinstall the theme after a Spotify update.

Strange. When Spotify updates it removes all my modifications with Spicetify and I have to re-run the install command.

**Comment by JulienMaille** [comment]
Usually you just need to run `spicetify backup restore apply`

**Comment by alixti** [comment]
> Usually you just need to run `spicetify backup restore apply`

Interesting. That command restores the old version and then applies the theme, sounds good but what about if the user wants the new version of Spotify with the theme. That was the idea of the batch file more or less.

**Comment by JulienMaille** [comment]
Looks like you should omit restore, I was wrong.
Have a look at the faq: https://github.com/khanhas/spicetify-cli/wiki/FAQ#spotify-got-an-update-i-ran-spicetify-apply-or-spicetify-update-now-my-spotify-is-totally-messed-up

**Comment by alixti** [comment]
> Looks like you should omit restore, I was wrong. Have a look at the faq: https://github.com/khanhas/spicetify-cli/wiki/FAQ#spotify-got-an-update-i-ran-spicetify-apply-or-spicetify-update-now-my-spotify-is-totally-messed-up

My idea was to update the theme as well.
