### ISSUE TITLE
Weird pill-shaped background on Playlist pages title

### ISSUE THREAD

**Issue by Davoleo** [JulienMaille/dribbblish-dynamic-theme#137]
**Describe the bug**
I think the pill shaped background on playlist titles looks kinda weird, is it intended or a visual bug?

**To Reproduce**
1. Open a playlist page
_Extra note: if you hover over the title the background will change opacity_

**Screenshots**
![image](https://user-images.githubusercontent.com/24458276/145609040-fe3975c6-04e1-4328-ae72-fe3fec241d80.png)

**Desktop Setup**
- Operating System: `Windows 10`
- Spotify: `Spotify for Windows - 1.1.74.631.g0b24d9ad`
- Spicetify: `v2.8.3`
- Dribbblish: `v4.1.0-61cbee1`

**Logs**
I don't think logs are really related to this issue but if you need them please tell me and I'll add them

**Comment by JulienMaille** [comment]
Spicetify is no compatible with 1.1.74, see https://github.com/khanhas/spicetify-cli/issues/1344

**Comment by SendNukez** [comment]
This is a bug, it is because the header counts as button, so button styles are applied to it. I have a fix for it but that messes up confirmation modals. Should be pretty easy to fix though.
