### ISSUE TITLE
bottom center and right edge shifted to the right

### ISSUE THREAD

**Issue by Inf4ge** [JulienMaille/dribbblish-dynamic-theme#14]
On certain songs -I only caught this bug in mozart's orchestra , maybe other songs have the same thing- the bottom center right edge are shifted to the right and that part aren't visible (off screen). However , the left side is still the same.

**To Reproduce**
Play Wolfgang Amadeus Mozart - Lecrimosa

![Screenshot_1](https://user-images.githubusercontent.com/69483795/124278506-03591080-db4f-11eb-9557-dec0b43ea051.png)
![Screenshot_3](https://user-images.githubusercontent.com/69483795/124278510-048a3d80-db4f-11eb-8ec7-f37604889b3c.jpg)

 - OS: Windows 10
 - Version 20H2

**Comment by JulienMaille** [comment]
can you reproduce this with original Dribbblish theme?

**Comment by Inf4ge** [comment]
idk why but original Dribbblish doesn't work for me.

**Comment by JulienMaille** [comment]
Then you should report this to @khanhas
