### ISSUE TITLE
Spinning Loading sign never goes away

### ISSUE THREAD

**Issue by Dr-DaNk** [JulienMaille/dribbblish-dynamic-theme#141]
Self explanatory, loading thing never goes away, I'm using latest spicetify and latest spotify versions. I would try and just disable the loading, but I can't, through the UI and I have no clue where the settings are stored file-wise.

**Comment by ps13g** [comment]
Spicetify version 2.8.3 currently does not support the latest 1.1.74 spotify version so we just have to wait till a fix is pushed out 
For more info check [khanhas/spicetify-cli#1344](https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/136)

**Comment by JulienMaille** [comment]
Try `spicetify restore backup apply`
