### ISSUE TITLE
Lyrics background color and dribbblish color consistency

### ISSUE THREAD

**Issue by nikko-guy** [JulienMaille/dribbblish-dynamic-theme#144]
It appears that spotify's lyrics feature uses a color related to the album image, so for consistency, it would make sense if dribbblish just used spotify's built-in color picker, or dribbblish overwrote spotify's choice.

**Comment by SendNukez** [comment]
We already have functionality to use Spotify's internal colorpicker (set `Settings > Theme > Color Selection Algorithm` to `Spotify`) but that's basically just Vibrant so it gets the same colors, and lyrics-plus is just better overall  imo. That said, it wouldn't hurt overhauling the internal lyrics feature's styles a bit. I'll add it to my list.
