### ISSUE TITLE
Feature Request: option to remove consistent floating time stamp

### ISSUE THREAD

**Issue by stfuwu** [JulienMaille/dribbblish-dynamic-theme#145]
While the theme itself works fine, I'd like an option where I could remove the floating time stamp and have it only show when I hover over the time bar. Thank you!

![Capture](https://user-images.githubusercontent.com/96242293/146374723-fc9bfff6-4cf0-449b-86b8-eca9dfab65a9.PNG)
)

**Comment by SendNukez** [comment]
Put this:
```css
.prog-tooltip {display: none;}
```
Into `Settings > Advanced > Custom CSS`
