### ISSUE TITLE
Keeping pure colour background on songs with artist profile artwork?

### ISSUE THREAD

**Issue by Azurastralis** [JulienMaille/dribbblish-dynamic-theme#146]
### alright time to get picky about fullscreen mode

This is a bit of a strange ask, but a feature I've been hoping for for a while is an optional toggle on keeping the album-art-matching colour background to fill the screen when in fullscreen, as opposed to the artist's background art on their page.

Not all songs do this - only for those with artists that do have a background on their profile. It can look pretty neat, but overall, I find the matching colour scheme to be significantly nicer.

Some examples so people know what I'm talking about:

> _**Artists without profile art get significantly larger album art in matching blank colour to their background**_

![Screenshot 2021-12-17 232343](https://user-images.githubusercontent.com/83326341/146628914-f38b6c45-b749-4d6d-abdb-ba0a87134f0a.png)

![Screenshot 2021-12-17 231625](https://user-images.githubusercontent.com/83326341/146628731-948d5a78-e048-4c38-bf31-93baa6e19933.png)

![Screenshot 2021-12-17 231930](https://user-images.githubusercontent.com/83326341/146628732-eedcfa3c-38c1-41b6-ba99-c7c7e9ff988e.png)

> _**Artists with profile art replace the blank colour with it and make the album art significantly smaller**_

![Screenshot 2021-12-17 231214](https://user-images.githubusercontent.com/83326341/146628484-87da054c-aa63-4b69-be1b-0b7de8564489.png)
_Staring down Ennio Morricone can be slightly menacing at times_

![Screenshot 2021-12-17 231132](https://user-images.githubusercontent.com/83326341/146628474-83e22c2d-1386-4483-93f9-aaba647a0dd6.png)

![Screenshot 2021-12-17 232948](https://user-images.githubusercontent.com/83326341/146628917-372cc0d2-3157-4a68-a1e3-e1085fb773d6.png)

> ______________________________________________________________________________________________

I certainly don't always mind the artwork, even it can clash a bit weirdly, but there's a nice simplicity to the pure colours that I'd love to see in uniformity for every song.

I hope this didn't come off as nitpicky or anything - it's been in my head for a while, and I noticed there was a feature suggestion forum and took the inspiration. I'm not sure if it's possible for there to be a toggle for this (or if there perhaps is one hidden deep in the features, though I've rooted through and had no luck), but if so, it'd definitely be a thing I wouldn't mind seeing. 

Thanks for reading, have a good one 👍 

-smasanomas

**Comment by SendNukez** [comment]
You can use `Settings > Advanced > Custom CSS` and put this there:
```css
.npv-background-image {display: none}
```
As for a toggle for this, I'll maybe redesign the fullscreen mode in the future and add this as an option.

**Comment by Azurastralis** [comment]
> You can use `Settings > Advanced > Custom CSS` and put this there:
> 
> ```css
> .npv-background-image {display: none}
> ```
> 
> As for a toggle for this, I'll maybe redesign the fullscreen mode in the future and add this as an option.

This is exactly what I was looking for. Thanks!
