### ISSUE TITLE
No word break between album title and release date in Playbar

### ISSUE THREAD

**Issue by lemonnuggets** [JulienMaille/dribbblish-dynamic-theme#147]
**Describe the bug**

**To Reproduce**
1. Enable `Show Album Info in Playbar` in settings

**Screenshots**
![image](https://user-images.githubusercontent.com/63046776/146768231-77d811f5-8919-4e1a-a8f8-7f56dd36116a.png)

Should preferably add a word break between the album title and release date instead of the word break happening inside the last word of the album title.

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.22000`
Spotify: `v1.1.74.631`
Spicetify: `v2.8.3`
Dribbblish: `v4.1.1-0e50a92`

**Extensions**
- bookmark.js
- fullAppDisplay.js
- keyboardShortcut.js
- popupLyrics.js
- shuffle+.js
- playNext.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.1.1",
    "showLoadingScreen": true,
    "openSettingsInfo": true,
    "showSearchBox": true,
    "rightBigCover": false,
    "roundSidebarIcons": true,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "winTopBar": "none-padding",
    "playbarShadow": true,
    "playbarTransition": true,
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": false,
    "fadeDuration": 0.5,
    "customCss": "",
    "colorSelectionAlgorithm": "colorthief",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "system",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "bgTheme": "bw"
}
```

**Comment by SendNukez** [comment]
Having a line break between album and release would make it too tall, the info should either be wider or capped with `...`. I added this to my list

**Comment by JulienMaille** [comment]
isn't it already handle by a scrolling text effect?

**Comment by JulienMaille** [comment]
It looks like this with spicecity-default theme:
![image](https://user-images.githubusercontent.com/182520/147403402-8fdc96ec-198d-4e37-8a7b-b564a5a5babd.png)

**Comment by JulienMaille** [comment]
@SendNukez this is caused by https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/6f7096baa3eeef5cb2193f569ba8e0d946ec07aa and the fact that you force a `display: block` which prevents `standalone-ellipsis-one-line` from doing its job.
Can you give it a look?
