### ISSUE TITLE
repeated search bars, missing song icons, elements missing

### ISSUE THREAD

**Issue by jitterdev** [JulienMaille/dribbblish-dynamic-theme#148]
![image](https://user-images.githubusercontent.com/64605731/147136713-3e53ef75-d8b8-4004-b57e-357a0c7c9b43.png)
After a spotify update, my theme broke. 

Spicetify version 2.8.1
Windows 10
Latest Dribbblish version

**Comment by SendNukez** [comment]
What version of Spotify did you update to?

**Comment by jitterdev** [comment]
> What version of Spotify did you update to?

![image](https://user-images.githubusercontent.com/64605731/147276872-90fe589c-fdd1-4bf9-9461-3cefe6b2451f.png)

**Comment by SendNukez** [comment]
Have you tried running `spicetify restore backup apply`?

**Comment by jitterdev** [comment]
> Have you tried running `spicetify restore backup apply`?

Reinstalled spotify to fix version mismatch, now looks like this.
![image](https://user-images.githubusercontent.com/64605731/147279902-1000178d-5628-4c2b-ac13-72b883013938.png)

After a couple seconds, more things disappeared.
![image](https://user-images.githubusercontent.com/64605731/147279928-4abfc832-89b5-4b33-a579-9b80930adeff.png)

**Comment by SendNukez** [comment]
Is there any dev console output?

**Comment by jitterdev** [comment]
> Is there any dev console output?

Sorry for the late response.
![image](https://user-images.githubusercontent.com/64605731/147498651-ffd2d99e-b6ce-40e4-918c-e26a2c2ba98f.png)

**Comment by SendNukez** [comment]
You should probably update to Spicetify v2.8.3 since you're using Spotify 1.74.

**Comment by jitterdev** [comment]
> You should probably update to Spicetify v2.8.3 since you're using Spotify 1.74.

Fixed! Had no idea that my Spicetify wasn't at the latest release. Theme working correctly now.
