### ISSUE TITLE
Wrong volume slider color on hover

### ISSUE THREAD

**Issue by Edick1337** [JulienMaille/dribbblish-dynamic-theme#149]
1. Hover on volume slider and see that it's green even if another color is selected

**GIF:**
![Ld2FUv1rOU](https://user-images.githubusercontent.com/20341452/147370303-a1de66d9-254a-4821-b1ff-caf0d5cca3f6.gif)

**P.S.** Installed from marketplace

**Edit:** same thing happens while hovering on track progress bar

**Comment by SendNukez** [comment]
Yeah currently the marketplace version is kind of bugged, I'll have to look into that. For the time being I'd just install the "normal" way.

**Comment by Edick1337** [comment]
Also the "like" heart is green and on hover it matches with current color
**GIF:**
![lfLmavGKtj](https://user-images.githubusercontent.com/20341452/147370857-b1e31349-de72-41b6-8bd9-e801c30d8f81.gif)

Maybe it's better to make the other way around?

**Comment by Edick1337** [comment]
> Yeah currently the marketplace version is kind of bugged, I'll have to look into that. For the time being I'd just install the "normal" way.

Oh okay, didn't know the marketplace and "normal" versions differ

**Comment by JulienMaille** [comment]
which part would only bug with the marketplace version?

**Comment by SendNukez** [comment]
Idk, the marketplace version doesn't quite look right so I guess the styles are bugged in some way

**Comment by Edick1337** [comment]
After updating to latest version this bug has appeared even in not-marketplace version
**GIF:**
![Spotify_5RT7zgDPle](https://user-images.githubusercontent.com/20341452/155983935-49ea59da-1723-4eed-96d4-37f5f6b36f59.gif)

**Comment by JulienMaille** [comment]
work as intended

**Comment by Edick1337** [comment]
changing sliders color to white - work as intended?
