### ISSUE TITLE
[BUG] Dropdown Text invisible

### ISSUE THREAD

**Issue by SendNukez** [JulienMaille/dribbblish-dynamic-theme#15]
**Describe the bug**
The Dropdown Menu on select Elements has invisible Text.

**To Reproduce**
Go to Settings and click on any Dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/29760988/124384556-18aa7800-dcd2-11eb-8bd8-c1457f3c04fb.png)

**Desktop (please complete the following information):**
Windows 10 Build 19043

**Logs**
![image](https://user-images.githubusercontent.com/29760988/124384636-92426600-dcd2-11eb-87de-700ca5c00931.png)

**Comment by JulienMaille** [comment]
I'm sorry but I can't reproduce it
![image](https://user-images.githubusercontent.com/182520/124396933-e66a3c00-dd0c-11eb-9358-48d20e21e7a6.png)
