### ISSUE TITLE
Names of playlists / folders glitch when scrolling the left panel with folders expanded

### ISSUE THREAD

**Issue by DroidZed** [JulienMaille/dribbblish-dynamic-theme#151]
**Describe the bug**
Whenever I scroll the left panel with folders expanded or folded I see this weird glitch of the names for a split second and turn back to normal. It is consistent and doesn't stop by simply folding and unfolding the folders again.

**To Reproduce**
1. Have a bunch of playlists / folders in the left panel.
2. Expand the folders once then fold them again.
3. Scroll the lists of the playlists / folders up and down

**Screenshots**
![Glitch-Spotify](https://user-images.githubusercontent.com/41507665/147775940-0e00a5d6-894b-4726-8c25-789262fefd9f.gif)

**Logs**

![image](https://user-images.githubusercontent.com/41507665/147773781-34c36768-88d8-4798-b03a-73aba05841b8.png)

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.18363`
Spotify: `v1.1.74.631`
Spicetify: `v2.8.3`
Dribbblish: `v4.1.1-0e50a92`

**Extensions**
- fullAppDisplay.js
- popupLyrics.js
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.1.1",
    "showLoadingScreen": true,
    "openSettingsInfo": true,
    "showSearchBox": true,
    "rightBigCover": true,
    "roundSidebarIcons": true,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 8,
    "sidebarGapRight": 32,
    "winTopBar": "none-padding",
    "playbarShadow": true,
    "playbarTransition": true,
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": true,
    "fadeDuration": 0.9,
    "customCss": ".main-trackList-trackList.main-trackList-indexable[aria-colcount=\"5\"] .main-trackList-trackListRowGrid {\n    background-color: var(--spice-main);\n}\n",
    "colorSelectionAlgorithm": "colorthief",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "bgTheme": "bw"
}
```

**Comment by JulienMaille** [comment]
Might be related to https://github.com/JulienMaille/dribbblish-dynamic-theme#important
How does it work with other themes?

**Comment by DroidZed** [comment]
The Dribblish normal one doesn't have this issue afaik. The patch you provided is already applied when using the automatic install so I don't think that's the issue.

**Comment by DroidZed** [comment]
Same thing, and I also noticed that the bug also appears with folders folded.

**Comment by DroidZed** [comment]
Still nothing ?
