### ISSUE TITLE
Allow setting spotify path in patch-dark-mode.ps1

### ISSUE THREAD

**Issue by danielphan2003** [JulienMaille/dribbblish-dynamic-theme#155]
**Is your feature request related to a problem? Please describe.**
I installed spotify and spicetify via https://github.com/TheRandomLabs/Scoop-Spotify.
In scoop, spotify path is located at `$env:HOMEDRIVE$env:HOMEPATH\scoop\apps\spotify-latest\current\Spotify.exe`

**Describe the solution you'd like**
Allow setting spotify path in patch-dark-mode.ps1 via command arguments, defaulting to `$env:APPDATA\Spotify\Spotify.exe` when none is specified

**Describe alternatives you've considered**
Manually editing the file and use a different path, but I want to upstream it instead.

**Additional context**
None.

**Comment by JulienMaille** [comment]
Is there a way we can obtain the path to Spotify from powershell?

**Comment by danielphan2003** [comment]
Oops, didn't mean to close this. I suppose `spicetify config spotify_path` would be good enough.

**Comment by danielphan2003** [comment]
Ugh, I really need to hide the close button @.@

**Comment by danielphan2003** [comment]
Closed in https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/f9c30d230aa58ad2062f1274d18af5dd84a6c69a
