### ISSUE TITLE
Window Controls does not disappear even with --transparent-window-controls

### ISSUE THREAD

**Issue by tactTsun** [JulienMaille/dribbblish-dynamic-theme#158]
Description
The theme is amazing, but I cannot seem to remove the window controls even if I type --transparent-window-controls. I apologize in advance if I couldn't give enough info for this is my first time.

To Reproduce
1.  Spotify Properties
2. Target: C:\Users\ayani\AppData\Roaming\Spotify\Spotify.exe --transparent-window-controls
3. Open Spotify

Screenshots
(https://imgur.com/a/QFUqw7n)

Desktop Setup
- Operating System: 
- Spotify: 
- Spicetify: 
- Dribbblish:

**Comment by JulienMaille** [comment]
Unfortunately this is the best you can do.
