### ISSUE TITLE
An alternative mode where the Playlist (or album) affects the theme

### ISSUE THREAD

**Issue by notlethiwe** [JulienMaille/dribbblish-dynamic-theme#159]
An alternative mode where the Playlist (or album) art affects the theme instead of the song currently playing would be really cool for those that have varied songs in a playlist and don't like the constant and drastic colour changes.

**Comment by SendNukez** [comment]
This has been on my list for a while now, just didn't have the time to implement this.

**Comment by notlethiwe** [comment]
ok

**Comment by JulienMaille** [comment]
Unfortunately, our ressources are limited and mostly spent on fixing what Spotify breaks with each update.
Contributions are welcomed though.
