### ISSUE TITLE
[BUG] Progress Bar Doesn't Move Up

### ISSUE THREAD

**Issue by Wist9063** [JulienMaille/dribbblish-dynamic-theme#16]
**Describe the bug**
Progress bar doesn't move up when another device is playing music.

**To Reproduce**
1. Play music on another device. 

**Screenshots**

![image](https://user-images.githubusercontent.com/22089269/124547111-7c22cb80-dde0-11eb-8c1d-d95223d16fcd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 21H1

**Logs**
![image](https://user-images.githubusercontent.com/22089269/124547307-c906a200-dde0-11eb-9a24-bf96099c83e0.png)

**Comment by JulienMaille** [comment]
Can you check if this happens also with the original Dribbblish theme? Thank you

**Comment by Wist9063** [comment]
Yep, it appears on Dribbblish regular.
