### ISSUE TITLE
Hide Light/Dark icon

### ISSUE THREAD

**Issue by tomini** [JulienMaille/dribbblish-dynamic-theme#160]
Hi,
is it possible to add toggle for hiding the Light/Dark icon? Or at least make the icon dark as while using dark mode it draws attention too much...
![image](https://user-images.githubusercontent.com/41676221/151225199-6300f66a-e14f-4fb8-ba96-3142d57ed281.png)
Thanks a lot!

**Comment by JulienMaille** [comment]
There's no such icons in this theme, check you setup you must have left-overs from another theme.

**Comment by tomini** [comment]
> There's no such icons in this theme, check you setup you must have left-overs from another theme.

Where should I look? I used Spicetify V1 and I never dealt with anything like this before.
I had only your two Dynamic themes that I uninstalled using the commands. Well, the first time I did a mistake and installed the DefaultDynamic using Marketplace and it did not work, so I removed it and proceeded with Powershell installation method.

Thanks.

**Comment by JulienMaille** [comment]
It probably comes from DefaultDynamic and the fact that the marketplace is still buggy.
