### ISSUE TITLE
Feature Request: Provide Windows Top Bar Solid & Transparent settings with padding

### ISSUE THREAD

**Issue by Tp-danny** [JulienMaille/dribbblish-dynamic-theme#163]
Currently you can select None, None with Padding (which makes the left-hand options menu look correct, or Transparent and Solid, both of which make the windows minimise, maximise, and close buttons look better, but fail to provide padding to the options menu.

The creation of a transparent padded and solid padded option would remedy this.

The screenshot below demonstrates the issue.

Transparent, but no padding makes left hand side look odd:
![image](https://user-images.githubusercontent.com/98900690/152189683-4fcd0bf9-7e98-43ac-8bae-fb9639b51452.png)

None with padding, but now windows options look odd:
![image](https://user-images.githubusercontent.com/98900690/152190201-62d39746-1dd8-4213-88e4-c5db43f01819.png)

A hybrid of these options would look best.

**Comment by cjboyle** [comment]
In the meantime, I've been happy with the following Custom CSS using "None (With Top Padding)":
```css
.Root {
  padding-top: 30px;
}
```

![image](https://user-images.githubusercontent.com/25211284/152626785-02dc0f4b-7c58-4a6b-ae94-255464ec9d7f.png)

**Comment by JulienMaille** [comment]
I don't think the hybrid suggestion is possible, we have no control over the drak background for min/max/close buttons.

**Comment by Davoleo** [comment]
just wondering, was that feature that made it possible for the window control buttons background to be transparent provided by spicetify? I remember using it at some point but then it stopped working, I believe you enabled it via a flag when launching spotify

**Comment by JulienMaille** [comment]
`--transparent-window-controls` https://github.com/khanhas/spicetify-cli/wiki/Spotify-Commandline-Flags

**Comment by Davoleo** [comment]
yeah that, apparently it's stopped working at all

**Comment by Tp-danny** [comment]
My suggestion is to have the transparent or solid options, but with the padding that shifts the 3 dots down, not to have the min/max/close buttons themselves move.

**Comment by Tp-danny** [comment]
Also yeah I can't get the transparent windows controls to work either.
