### ISSUE TITLE
Searchbar not focused when clicked on and being on another tab

### ISSUE THREAD

**Issue by DanBeast1337** [JulienMaille/dribbblish-dynamic-theme#166]
mentioned previously here [#1456 @ spicetify-cli](https://github.com/khanhas/spicetify-cli/issues/1456)

### **Describe the bug**
When clicking on the search bar, it's not focused anymore after it has loaded, when previously not being on the search page.

If you are on the search page, one click is enough to stay focused, otherwise you have to click on the search bar and click another time to focus again.

This can cause some irritation if wanting to search something and then instead using shortcuts for other things (i often removed songs from my favorites like this).

### **To Reproduce**
1. Click on search bar (while being on another tab) 
(2.) Click on search bar, while on search page

### **GIF showing the issue**
![2022-02-05_14h-09m-08s](https://user-images.githubusercontent.com/9980963/152643570-27cdb057-c0c2-48d2-99e4-153a68dcaa52.gif)

### **Desktop Setup**
OS: Windows v10.0.19041
Spotify: v1.1.78.765
Spicetify: v2.9.0
Dribbblish: v4.1.1-0e50a92

**Comment by JulienMaille** [comment]
@SendNukez had issued a fix in https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/c5fec9cbd1f1fa6ff947828eb4bbe31d740f6264 is it broken again?

**Comment by SendNukez** [comment]
Yes, but we haven't pushed a new release yet. It's probably time for a new one.
