### ISSUE TITLE
No UI response after leaving application open

### ISSUE THREAD

**Issue by lucasballr** [JulienMaille/dribbblish-dynamic-theme#167]
**Describe the bug**
After leaving the application open for a while with this theme activated, The program's UI will stop responding to user inputs. The only way to fix this that I have noticed is closing the app and opening it back up.

**To Reproduce**
1. Install this theme on spicetify
2. Leave application open for roughly 30 minutes
3. Return to application and observe the bug

**Desktop Setup**
- Operating System: Windows 10
- Spotify: Spotify for Windows 1.1.78.765.g5ea20b00
- Spicetify: 2.9.0
- Dribbblish: 
```
OS: Windows v10.0.19043
Spotify: v1.1.78.765
Spicetify: v2.9.0
Dribbblish: v4.1.1-0e50a92
```

**Comment by ShibuyaRyan** [comment]
This is also happening to me exactly.
The times that it happens is seemingly random. The UI locks up but I can still hear songs and use media keys.

OS: Windows v10.0.19044
Spotify: v1.1.78.765
Spicetify: v2.9.0
Dribbblish: v4.1.1-0e50a92

**Comment by JulienMaille** [comment]
Can you guys open the dev console in advance so you can still look for errors when it freezes?

**Comment by lucasballr** [comment]
Apologies if this is a stupid question. Would it be possible for you to show how to open then dev console? I've been looking it up and can't find any information on it.

**Comment by JulienMaille** [comment]
Add logs from console. To do that
 1. Run `spicetify enable-devtool` in terminal
 2. Spotify will be restarted
 3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
 4. Navigate to tab Console
 5. Copy console window content.

**Comment by SendNukez** [comment]
I can not reproduce this. I always leave Spotify open all day and it has never frozen for me. Could you also try with a different theme and see if it is not a Spotify / Spicetify issue?

**Comment by Davoleo** [comment]
It's happens to me in a while, when I opened dev tools I discovered that they're unresponsive as well, sounds like some kind of graphic engine crash
![image](https://user-images.githubusercontent.com/24458276/154342269-5d991e26-5e19-4f8a-a6a7-552824688b99.png)
I can write in the console but no errors where there when I opened it

another thing I noticed is that the UI got stuck with this weird color combination, so could it be that it was a song cover that broke the color selection algorithm in some way?
![image](https://user-images.githubusercontent.com/24458276/154342818-c678e7d7-b112-4cec-9484-e25efb4f3b61.png)


just writing some things I noticed, maybe they'll help in finding the cause of this

**Comment by SendNukez** [comment]
> I can not reproduce this. I always leave Spotify open all day and it has never frozen for me. Could you also try with a different theme and see if it is not a Spotify / Spicetify issue?

Now that I think about it, this could be an issue with Spotify being in the background for long amounts of time, I have a monitor that is almost exclusively for Spotify, so it is always in the foreground. Maybe that is why it has never happened to me?

**Comment by JulienMaille** [comment]
Reopen this if you can help us reproduce that issue, ie. if you can narrow it down to a specific song or playlist

**Comment by Tnings** [comment]
I've been having this issue too, it's caused for me by having spotify open and playing a song on another virtual desktop for too long. It usually freezes randomly when playing another song in the queue. It has happened to me many times on may different playlists and just now happened when I finished listening to "I Need a Lover" by Pat Benatar and "Love is a Battlefield" started playing.

Like I mentioned before that is not the only case where this happens, but this is the only one I can remember easily. 

I am on MacOS 12.0.1 and Spicetify 2.9.8

Also, idk what causes this problem to stop but after restarting my laptop sometimes the problem goes away, but not when quitting and launching spotify again.

I hope this narrows it down a bit

**Comment by Tnings** [comment]
also here is the devtools console output
<img width="750" alt="image" src="https://user-images.githubusercontent.com/55812511/167333802-438d9893-fd74-472f-8c36-a3e0cb88730f.png">
