### ISSUE TITLE
Play/Pause button isn't centered

### ISSUE THREAD

**Issue by Cornflix244** [JulienMaille/dribbblish-dynamic-theme#168]
**Describe the bug**

The play and the pause buttons are weirdly moved.

**To Reproduce**
1. I do not know how I did that

**Screenshots**

![image](https://user-images.githubusercontent.com/70451196/152822330-ca4c64f7-6f8e-4226-9ae9-b588926ab979.png)
![image](https://user-images.githubusercontent.com/70451196/152822440-2d9085f6-846d-420a-8e01-a25297bc64a4.png)

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.19042`
Spotify: `v1.1.78.765`
Spicetify: `v2.9.0`
Dribbblish: `v4.1.1-0e50a92`

**Extensions**
- fluent.js
- extension.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.1.1",
    "showLoadingScreen": true,
    "openSettingsInfo": true,
    "showSearchBox": true,
    "rightBigCover": true,
    "roundSidebarIcons": false,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "winTopBar": "none-padding",
    "playbarShadow": true,
    "playbarTransition": true,
    "playerControlsStyle": "dribbblish",
    "showAlbumInfoInPlaybar": true,
    "hideAds": true,
    "fadeDuration": 0.5,
    "customCss": "",
    "colorSelectionAlgorithm": "colorthief",
    "colorOverride": "#1ed760",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "bgTheme": "bw"
}
```

**Comment by JulienMaille** [comment]
fluent is from another theme right?

**Comment by Cornflix244** [comment]
> fluent is from another theme right?

Might be the problem, how do i remove it?

**Comment by Cornflix244** [comment]
> Run `spicetify config extensions fluent.js-`

Thank you, it solved my problem.
