### ISSUE TITLE
Where can I find SpotifyNoControl.exe ? Can't find it in the theme package.

### ISSUE THREAD

**Issue by Shagnikpaul** [JulienMaille/dribbblish-dynamic-theme#17]

**Comment by SweetyVolty** [comment]
came for this exactly, not in the folder.

**Comment by JulienMaille** [comment]
https://github.com/morpheusthewhite/spicetify-themes/blob/master/DribbblishDynamic/SpotifyNoControl.exe

**Comment by Shagnikpaul** [comment]
@JulienMaille Thank You very much !
