### ISSUE TITLE
With the new Sporify update, some titles are bigger than the space available

### ISSUE THREAD

**Issue by IrepY** [JulienMaille/dribbblish-dynamic-theme#171]
**Describe the bug**
The title and or album of a song sometimes overflows the bar at the bottom, as the new update introduced a bigger font I think.

**To Reproduce**
1. Update spotify to the newest version
2. Play a song with a long title, or with a long album name

**Screenshots**
![Screenshot 2022-02-18 213038](https://user-images.githubusercontent.com/82579394/154756957-e2d6296b-36af-4a8f-85ca-1f84d2defc42.png)

**Desktop Setup**
- Operating System: Windows 11 Home (22000.493)
- Spotify: v1.1.79.763
- Spicetify: v2.9.1
- Dribbblish: v4.1.1-0e50a92

**Comment by kyrie25** [comment]
Can confirm the bug is also present on my side

**Comment by JulienMaille** [comment]
Spotify breaks internal css with each new release, I'm not sure how Spicetify plans to easily handle that.
