### ISSUE TITLE
Experimental Features tab simply don't work

### ISSUE THREAD

**Issue by davimaiaa** [JulienMaille/dribbblish-dynamic-theme#172]
**Describe the bug**
By clicking in the 'Experimental Features' tab, nothing shows up as it should be

![image](https://user-images.githubusercontent.com/67204261/154826443-325211df-38ae-4335-a594-6767738de1cf.png)

**Desktop Setup**
- Operating System: Windows 11
- Spotify: <1.1.79.763.gc2965cdf>
- Spicetify: 2.9.1
- Dribbblish: 4.1.1

**Comment by JulienMaille** [comment]
See original bug report: https://github.com/khanhas/spicetify-cli/issues/1485

**Comment by davimaiaa** [comment]
> See original bug report: [khanhas/spicetify-cli#1485](https://github.com/khanhas/spicetify-cli/issues/1485)

Thanks!!!
