### ISSUE TITLE
Colour transition while on static mode

### ISSUE THREAD

**Issue by f1shy-dev** [JulienMaille/dribbblish-dynamic-theme#179]
**Describe the bug**
The theme changes colour to a dynamic colour then transitions back, when using the static theme. This is seen as a bug because it slows down performance and is useless for the static theme, and also doesn't look very good as it changes colour for a second and then back to the static colour. (It only seems to happen some of the time).

**To Reproduce**
Steps to reproduce the behaviour:
1. Set colour picking mode to static
2. Change between songs and see the colour change to dynamic-based for a second then back on song change.

**Screenshots**
(it happens a few times, then stops happening, then happens again when I change to a new song)

https://user-images.githubusercontent.com/56125930/155894849-106bd0a7-81a4-484e-ad62-148cc5562ec7.mov

**Desktop Setup**
- Operating System: MacOS 12.0 Beta
- Spotify: 1.1.79.763
- Spicetify: 2.9.1
- Dribbblish: vDev-local (on my PR version #178)

**Comment by JulienMaille** [comment]
Thanks for reporting, should be an easy fix

**Comment by SendNukez** [comment]
This will be fixed in the next release, thank you for reporting this.
