### ISSUE TITLE
[BUG] Text always gray

### ISSUE THREAD

**Issue by devilAPI** [JulienMaille/dribbblish-dynamic-theme#18]
**Describe the bug**
The text is always grey, making it look bad

**To Reproduce**

Install with auto installer
Open spotify

**Screenshots**
![weirdcolor](https://user-images.githubusercontent.com/52862870/124828791-02254a80-df78-11eb-8e07-064b16621b0f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Dynamic 1.6, Spotify 1.1.62.583

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Comment by JulienMaille** [comment]
Please look at your logs as explained in the bug template.
Please also share the content of `config-xpui.ini`

**Comment by devilAPI** [comment]
Nevermind i fixed it, for some reason `color_scheme` was set to `Nord-Dark`

**Comment by devilAPI** [comment]
#19
