### ISSUE TITLE
Recent update messed the theme up

### ISSUE THREAD

**Issue by aQL3XY** [JulienMaille/dribbblish-dynamic-theme#183]
**Describe the bug**
Multiple search bars have popped up and the theme does not reflect the colors of the songs as well as the back ground image of the album is missing.

**To Reproduce**
1. Fix the background image
2. Get the colors of the albums and music fixed 
3. lastly the search bar

**Screenshots**
![image](https://user-images.githubusercontent.com/99064321/156525044-e57339c0-0879-4080-a373-f7bb0f7526d6.png)

**Desktop Setup**
- Operating System: Windows 11
- Spotify: Spotify for Windows 1.1.80.699.gc3dac750
- Spicetify: spicetify latest 
- Dribbblish: 4.1.2

**Logs**

```console
Although devTools is allowed, does not allow to inspect it. 
```

**Comment by Adithya-Kalany** [comment]
Second this ^^^

**Comment by davimaiaa** [comment]
mine as well, and it don't even open with dribbblish.. 
![image](https://user-images.githubusercontent.com/67204261/156691538-e0480e40-200d-4a75-81b1-bb149538d4e7.png)

**Comment by ShadowAya** [comment]
same issue here

**Comment by JulienMaille** [comment]
Cannot reproduce, please clean reinstall spicetify and this theme.
