### ISSUE TITLE
Always loading in title bar

### ISSUE THREAD

**Issue by Question406** [JulienMaille/dribbblish-dynamic-theme#186]
**Describe the bug**
There's always a loading icon and text in title bar after launched. And I also meet this bug on my macbook.

**To Reproduce**
1.  install the latest release
2.  launch spotify

**Screenshots**
![bug](https://user-images.githubusercontent.com/15529162/156862165-3d2c0fe5-3726-4e0d-960c-defa5f9802ce.jpg)

**Logs**
I couldn't get to log tab after pressing `Ctrl + Shift + I` when devtools is enabled. Could someone help me with this?

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.19044`
  Spotify: `v1.1.80.699`
  Spicetify: `v2.9.2`
  Dribbblish: `v4.1.2-827c9f3`

  **Extensions**
  - dribbblish-dynamic.js
  - extension.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.2",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none",
      "playbarShadow": true,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": false,
      "showGenreInfoInPlaybar": false,
      "hideAdsOrPremium": "none",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "system",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by SendNukez** [comment]
The Devtools are currently broken, we'll have to wait for it to be fixed to debug this.

**Comment by JulienMaille** [comment]
Try this https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1106851885 and reopen if needed
