### ISSUE TITLE
Can't scroll in the Spotify's sidebar.

### ISSUE THREAD

**Issue by Rqph** [JulienMaille/dribbblish-dynamic-theme#187]
**Describe the bug**

When I try to scroll down in the sidebar to see some of my playlists, It doesn't move at all.

**To Reproduce**
1. I installed Spotify with the installer on Spotify website.
2. I installed spicetify and the dribblish dynamic theme with powershell.
3. That's it, I just can't scroll in the sidebar.

**Screenshots**

##

**Logs**

```console
[paste logs here]
```

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.22000`
  Spotify: `v1.1.80.699`
  Spicetify: `v2.9.2`
  Dribbblish: `v4.1.2-827c9f3`

  **Extensions**
  - dribbblish-dynamic.js
  - extension.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.2",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 35,
      "winTopBar": "transparent",
      "playbarShadow": true,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "hideAdsOrPremium": "none",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "system",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "grey"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
Please share the `[patch]` section content of your `config-xpui.ini` file
