### ISSUE TITLE
Hightlighting current playing song

### ISSUE THREAD

**Issue by glaicodes** [JulienMaille/dribbblish-dynamic-theme#189]
**Is your feature request related to a problem? Please describe.**
I'm frustated when I can't easily find the current playing song.
**Describe the solution you'd like**
Making the current playing song highlighted.

**Additional context**
![image](https://user-images.githubusercontent.com/75806392/156921880-f1b4b826-29d5-4984-a0fb-ecbe103a6e0d.png)

**Comment by SendNukez** [comment]
Yeah, I want to overhaul the entire playlist / album lists anyways because it bugs me that the numbers are not centered and when hovering over a track the playing icon is also not centered at all. We'll have to wait until the devtools get fixed though.
