### ISSUE TITLE
Album covers not being rounded edge in latest played

### ISSUE THREAD

**Issue by glaicodes** [JulienMaille/dribbblish-dynamic-theme#190]
**Is your feature request related to a problem? Please describe.**
It's annoying me when everthing else is a rounded edge while the album picture is not.

**Describe the solution you'd like**
Make album pictures in latest played rounded edge.

**Additional context**
![image](https://user-images.githubusercontent.com/75806392/156922332-061c31ed-87fd-4e9a-8f2d-479e6575d596.png)

**Comment by JulienMaille** [comment]
Will check this when devtool is fixed

**Comment by JulienMaille** [comment]
This is hard to fix due to spotify changing css classes every other week.
One workaround would be to reduce `--image-radius` to 4px
