### ISSUE TITLE
Different fonts

### ISSUE THREAD

**Issue by glaicodes** [JulienMaille/dribbblish-dynamic-theme#191]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I notice that there are a few different fonts used.
**Describe the solution you'd like**
Let us pick which fonts we would like to use. (spotify regular, dribbblish, or custom)

**Describe alternatives you've considered**
injectFont.js from https://canary.discord.com/channels/842219447716151306/842818627164962828/926826507224100884 but it didn't work.

**Additional context**
![image](https://user-images.githubusercontent.com/75806392/156922478-cabd3443-105a-4e7f-ba4f-03f7c9931112.png)

**Comment by JulienMaille** [comment]
Can't you do this using Settings > Advanced > Custom css
