### ISSUE TITLE
App will not start properly

### ISSUE THREAD

**Issue by dxnenderby** [JulienMaille/dribbblish-dynamic-theme#192]
**Describe the bug**
App reloads while having just a moment loading screen then eventually crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Dribblish Dynamic from the marketplace

**Desktop Setup**
- Operating System:  Windows 10 
- Spotify: <!-- Cannot get on the app to find out
- Spicetify: 2.9.2
- Dribbblish:  Same with Spotify Version

https://user-images.githubusercontent.com/81931624/157291845-c15cee3a-c712-43a9-add5-2dba10cb3f3f.mp4

**Comment by JulienMaille** [comment]
Can you please open a bug on the marketplace extension?
