### ISSUE TITLE
Enhance logo sticking out

### ISSUE THREAD

**Issue by glaicodes** [JulienMaille/dribbblish-dynamic-theme#193]
**Is your feature request related to a problem? Please describe.**
Enhance logo sticking out annoys me.

**Describe the solution you'd like**
Move the enhance logo next to the song name

**Additional context**
![image](https://user-images.githubusercontent.com/75806392/157508045-acfbf921-1c83-4f04-a14f-09d104e1876d.png)

**Comment by SendNukez** [comment]
The devtools are currently broken, we'll have to wait for it to be fixed to investigate this.
