### ISSUE TITLE
Playlist descriptions do not change font color in Light Mode, making it impossible to read them

### ISSUE THREAD

**Issue by keef-khan** [JulienMaille/dribbblish-dynamic-theme#198]
**Describe the bug**
The descriptions of any playlists do not display in a legible font color which makes it almost impossible to read and toggling dark mode does not fix it. The text is only legible in dark mode.

**To Reproduce**
1. Activate light/daytime mode within Dribbblish

**Screenshots**
<img width="415" alt="Screen Shot 2022-03-18 at 7 53 22 PM" src="https://user-images.githubusercontent.com/67087783/159097987-d521910a-015b-4593-aed9-0097fa7a2fe2.png">

**Logs**

```console
was not able to get dev tool to work correctly. console reported it as activated but keyboard shortcut did not work, nor did it appear in the menu bar as an option. 
```

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Osx v12.3.0`
  Spotify: `v1.1.81.604`
  Spicetify: `v2.9.2`
  Dribbblish: `v4.1.3-8c5a45c`

  **Extensions**
  - dribbblish-dynamic.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.3",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": false,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": false,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none-padding",
      "playbarShadow": false,
      "playbarTransition": true,
      "playerControlsStyle": "spotify",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "hideAdsOrPremium": "both",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "vibrant",
      "colorOverride": "#033e00",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "system",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
can't do anything until the dev tools are restored by Spicetify team
