### ISSUE TITLE
Colors do not change anymore in Spotify

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#199]
**Describe the bug**
Color does not change dynamically anymore
**To Reproduce**
1. Open Spotify
2. Play any song
3. Skip to the next song

**Screenshots**
<img width="1280" alt="Screen Shot 2022-03-20 at 10 02 43 AM" src="https://user-images.githubusercontent.com/84423124/159171346-38b49e55-271a-4c53-ba4b-746add6caaea.png">
<img width="1275" alt="Screen Shot 2022-03-20 at 10 03 00 AM" src="https://user-images.githubusercontent.com/84423124/159171351-126ca043-8251-42b6-8e83-06670bab74b7.png">
<img width="644" alt="Screen Shot 2022-03-20 at 10 04 07 AM" src="https://user-images.githubusercontent.com/84423124/159171360-7afd7bfa-1814-42a1-b75c-868e7fb422fa.png">

  **Versions**
OS: Osx v12.3.0
Spotify: v1.1.81.604
Spicetify: v2.9.2
Dribbblish: v4.1.3-8c5a45c

  **Extensions**
  - dribbblish-dynamic.js
  - fullAppDisplay.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.3",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none-padding",
      "playbarShadow": false,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": false,
      "showGenreInfoInPlaybar": false,
      "hideAdsOrPremium": "none",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#02deed",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "dark",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by IrepY** [comment]
Can confirm, same versions, also doesn't work for me

**Comment by f1shpie** [comment]
I'm having the same issue on Windows 10.

**Comment by davimaiaa** [comment]
same

**Comment by Mcfly2340** [comment]
same for me but there is a very random delay most of the time. sometimes it changes halfway into the next song or just gets stuck on one color

**Comment by ps13g** [comment]
Reopening this issue because this now occurs in 
OS: macOS v12.3.1
Spotify: v1.1.83.956
Spicetify: v2.9.6
Dribbblish: v4.1.4-239033a
