### ISSUE TITLE
Color stops changing after a local file has played

### ISSUE THREAD

**Issue by kallekalle** [JulienMaille/dribbblish-dynamic-theme#20]
Title says it all, the UI color will remain on the color of the song played before the local file, and won't change until you restart Spotify. I'll be happy to provide any logs or evidence of this if needed :)

**Comment by JulienMaille** [comment]
Yes please share some logs, it will help a lot

**Comment by kallekalle** [comment]
I hope this is the right thing lol

https://user-images.githubusercontent.com/86068227/125190887-c9b79200-e23f-11eb-9caf-9552de7c4f29.mp4

**Comment by JulienMaille** [comment]
weird, the log do not really help. I will try to reproduce this on my side

**Comment by kallekalle** [comment]
This is on an M1 Mac running macOS 12.0 Beta (21A5268h), Spotify version 1.1.62.583.gdac868ed-a. I'll try to reproduce this on my Windows machine

**Comment by Macilvoy** [comment]
I have the same problem. 
spotify 1.1.65.643.g2d707698-a 
W10 21H1 19043.1110
