### ISSUE TITLE
Podcast Genre/Album Info bug

### ISSUE THREAD

**Issue by HideOnFluff** [JulienMaille/dribbblish-dynamic-theme#200]
**Describe the bug**
After playing any podcast, the genre or album info of any song won't update and will be stuck with the wrong information.

**To Reproduce**
1.  Open Spotify
2.  Play a Podcast episode of your choice
3.  Go to any playlist with songs instead of episodes
4. Play any song

**[I also made a video showing the problem](https://i.imgur.com/3xhe1Px.mp4)**

**Screenshots**

![image](https://user-images.githubusercontent.com/83287502/159869547-7f39063d-c53f-47af-bcdb-fc2b5ee28327.png)

**Logs**

```console
Sorry but I couldn't make this work.
```

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.22581`
  Spotify: `v1.1.81.604`
  Spicetify: `v2.9.2`
  Dribbblish: `v4.1.3-8c5a45c`

  **Extensions**
  - omni.js
  - fullAppDisplay.js
  - dribbblish-dynamic.js
  - turntable.js
  - .js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.3",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": true,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "transparent",
      "playbarShadow": true,
      "playbarTransition": true,
      "playerControlsStyle": "spotify",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": true,
      "hideAdsOrPremium": "none",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "luminance",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "dark",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
Can you have a look at latest build?

**Comment by HideOnFluff** [comment]
sorry but I'm not quite sure how to do so, I've only been installing final releases.

**Comment by ps13g** [comment]
> Can you have a look at latest build?

How do we do this since there is no build that was released.

**Comment by SendNukez** [comment]
Should be in the latest release now. Also, to download and test dev builds you can go to [Actions / Webpack Test](https://github.com/JulienMaille/dribbblish-dynamic-theme/actions/workflows/webpack-test.yml), click on the latest run, download the artifact (called something like `DribbblishDynamic_vBeta-1064087`) by clicking on its name and install using the [Manual](https://github.com/JulienMaille/dribbblish-dynamic-theme#manual-install) installation steps.
