### ISSUE TITLE
Album info and Genre info just adds blank rows

### ISSUE THREAD

**Issue by Mcfly2340** [JulienMaille/dribbblish-dynamic-theme#201]
**Describe the bug**
Both the options Album info and Genre info don't do anything but sometimes add blank rows underneath the currently playing songs' artist. Show Album Info in Playback is on by default but it doesn't work, when I download the external extension to show Genre info from the marketplace it does work whether the option is enabled in the Dribbblish Settings or not. But I can't get the Album info to work at all 

**To Reproduce**
1. Open the Dribbblish Settings
2. Scroll down to playbar and expand it
3. Enable show album info in playbar if not enabled already
4. Enable show genre info in playbar

**Screenshots**
it doesn't really show in the screenshot but I'll include it anyway
![image](https://user-images.githubusercontent.com/71077562/160096525-58c1defa-ecfd-4026-b321-ed879ecb7102.png)

**Desktop Setup**
- OS: Windows v10.0.22581
- Spotify: v1.1.81.604
- Spicetify: v2.9.3
- Dribbblish: v4.1.3-8c5a45c

**Logs**

**Comment by JulienMaille** [comment]
Can you try last update?

**Comment by Mcfly2340** [comment]
> Can you try last update?

yeah it's back, thanks!
