### ISSUE TITLE
DevTools shortcut doesn't do anything

### ISSUE THREAD

**Issue by Mcfly2340** [JulienMaille/dribbblish-dynamic-theme#202]
**Describe the bug**
when hitting ctrl + shift + i my cursor loads for half a second and then doesn't do anything

**To Reproduce**
1.  in a terminal window say `spicetify enable-devtools`
2. use the shortcut ctrl + shift + i

**Desktop Setup**
- OS: Windows v10.0.22581
- Spotify: v1.1.81.604
- Spicetify: v2.9.3
- Dribbblish: v4.1.3-8c5a45c

**Comment by Davoleo** [comment]
This is a spicetify-cli issue - ref: https://github.com/spicetify/spicetify-cli/issues/1518

**Comment by Mcfly2340** [comment]
Yeah, didn't think clearly. Sorry about that.
Thanks for the reply thought, appreciate it
