### ISSUE TITLE
Play/Pause button not visible

### ISSUE THREAD

**Issue by adnan1710** [JulienMaille/dribbblish-dynamic-theme#205]
**Describe the bug**
The Play/Pause button in Playbar isn't visible.

**Screenshots**
![spotify](https://user-images.githubusercontent.com/72688100/160687947-8f76090f-e527-4738-948d-f4cc02f90e8f.png)

**Desktop Setup**
OS: Windows 11 (v10.0.22000)
Spotify: v1.1.81.604
Spicetify: v2.9.4
Dribbblish: v4.1.4-239033a

**Comment by JulienMaille** [comment]
Cannot reproduce
