### ISSUE TITLE
Issues with theming in Search menu (broken textures)

### ISSUE THREAD

**Issue by TrashTaste1** [JulienMaille/dribbblish-dynamic-theme#212]
**Describe the bug**
After clean installing and applying the theme the Search menu seems to have broken textures (Screenshot 1) and also all the menus start scrolled all the way down causing the navigation bar at the top to overlap with the title of the menu (Screenshot 2).

**To Reproduce**
1. Just performing a clean install causes this issue to appear every single time for me.

**Screenshots**

![Screenshot1](https://user-images.githubusercontent.com/103210392/162260863-7f05c6b7-a471-45ad-95c8-28e1fcd3aeaa.png)

![Screenshot2](https://user-images.githubusercontent.com/103210392/162260867-fbd6646b-4d4f-4824-9f9f-f6cfc4cdf572.png)

**Desktop Setup**
OS: Windows v10.0.22581
Spotify: v1.1.81.604
Spicetify: v2.9.4
Dribbblish: v4.1.4-239033a

**Comment by JulienMaille** [comment]
How should it look like?
