### ISSUE TITLE
Broken adblock

### ISSUE THREAD

**Issue by sanctifyy** [JulienMaille/dribbblish-dynamic-theme#213]
**Describe the bug**
The built in adblock does not work and i am still receiving both audio and visual ads

**To Reproduce**
1. 
run the app?

**Screenshots**
![image](https://user-images.githubusercontent.com/87588511/162330576-94fdbd40-f262-4209-bcc4-30f81f2ce610.png)

**Logs**

```console
[paste logs here]
```

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.19043`
  Spotify: `v1.1.81.604`
  Spicetify: `v2.9.4`
  Dribbblish: `v4.1.4-239033a`

  **Extensions**
  - omni.js
  - dribbblish-dynamic.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.1.4",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": false,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "solid",
      "playbarShadow": true,
      "playbarTransition": false,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "hideAdsOrPremium": "both",
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "dark",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
@SendNukez I'm afraid adblock had nothing to do in this theme in the first place. Would you mind cleaning it out?

**Comment by SendNukez** [comment]
Yeah, I'll remove it.

**Comment by SendNukez** [comment]
I'll just comment it out and leave the CSS for now. Maybe I'll fix it in the future when devtools are less annoying to open.

**Comment by JulienMaille** [comment]
> I'll just comment it out and leave the CSS for now. Maybe I'll fix it in the future when devtools are less annoying to open.

Try this: https://github.com/ririxidev/spotifyEnableDevTools/releases
