### ISSUE TITLE
Spotify loading endlessly

### ISSUE THREAD

**Issue by actuallylost** [JulienMaille/dribbblish-dynamic-theme#216]
**Describe the bug**

**To Reproduce**
1. Have Dribbblish Dynamic theme installed
2. Update Spicetify to latest
3. (Potentially optional) After updating run `spicetify backup apply`
4. Observe

**Screenshots**
[What I see](https://i.imgur.com/Dj3SmgF.png)

**Desktop Setup**
- Operating System: Windows 10
- Spotify: Can't access (probably latest)
- Spicetify: 2.9.5
- Dribbblish: Latest (just updated)

**Logs**

```console
cannot open devtools
```

**Comment by alexhulbert** [comment]
I'm also having this issue. Unfortunately, downgrading Spotify to v1.1.72.439 didn't help.

**Comment by ToasterDEV** [comment]
I can confirm the same happens with downgraded version 1.1.78.765 of the Spotify App on Windows 11 x64 and Spicetify version 2.9.5, the DevTools logs report the following at launch:

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED xpui.app.spotify.com/:1 

Uncaught SyntaxError: Unexpected token ',' xpui.js:1 

DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

Uncaught Error: ready timeout
    at Dribbblish.js:48:1
(anonymous) @ Dribbblish.js:48 Dribbblish.js:48 
```
The last error in particular increases its counter by the second since the app is opened.

If there's any more information required please just tell me so and I shall post it. Thanks for the help!

**Comment by Rajbir98** [comment]
Just Updated Issue Still Occurs

**Comment by JulienMaille** [comment]
Do you all have the marketplace extension?

**Comment by actuallylost** [comment]
Same here

**Comment by cadeteh** [comment]
same here, though by after reinstalling a bunch of times, I was able to see that when I open spotify whenever the spotify installer comes is when it crashes.

**Comment by Rajbir98** [comment]
> Do you all have the marketplace extension?

I don't like it so I don't

**Comment by Rajbir98** [comment]
I degraded Spotify to use it

**Comment by alexhulbert** [comment]
If it helps, a fresh install with the marketplace extension installed and enabled also produces the same problem on my machine.

**Comment by CrypticBridge** [comment]
I found a workaround after a fresh install of Spotify, Spicetify, the marketplace extension, and Dribbblish Dynamic.

If you turn off the “Show Loading Screen Setting” in the Dribbblish Settings the first time the theme is installed, you'll still encounter the theme not fully taking place every subsequent time Spotify is launched.

You should be able to navigate to the Marketplace though, and then open and close marketplace settings to force Spotify and the theme to refresh, and from that point everything seems to work fine. You'd just have to do that every time you open Spotify.

However, I did find that having Spotify autostart with Windows allowed everything to work properly until I closed Spotify, and then I'd have to go through the process above again.

**Comment by Davoleo** [comment]
Got Dev Tools working this is the line at which the error is occurring in my setup:
![image](https://user-images.githubusercontent.com/24458276/164713552-5be943a3-35de-47ba-a2c5-1ecffcbdf6bd.png)

**Comment by vvirtues** [comment]
can confrim, spotify just updated, mightve been the problem

**Comment by t2trappy** [comment]
what i did was completely remove spicetify by running this in powershell
<code>
cd ~
</code>
<code>
rm -r spicetify-cli
</code>
<code>
rm -r .spicetify
</code>
then i reinstalled spotify and it worked! another easy fix though is by just using 
<code>
$v="2.9.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
</code>
this method worked for me, 2.9.1 seems to not have this issue

**Comment by ps13g** [comment]
> what i did was completely remove spicetify by running this in powershell ` cd ~ ` ` rm -r spicetify-cli ` ` rm -r .spicetify ` then i reinstalled spotify and it worked! another easy fix though is by just using ` $v="2.9.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression ` this method worked for me, 2.9.1 seems to not have this issue

^^^ Works for me on macOS on the newest version of Spotify (1.1.83.956.gbe7ea9a7) by using 
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh -o /tmp/install.sh
sh /tmp/install.sh 2.9.5`

**Comment by alexhulbert** [comment]
I went into a live usb and tried installing everything from scratch with the latest versions of everything (2.9.7 of Spicetify-cli, 4.2.0 of this theme, and 1.1.84.716.gc5f8b819 of Spotify) and I'm getting the same error. I'm not sure what I could possibly be doing differently. Has anyone else solved the issue?

**Comment by ps13g** [comment]
=Has anyone else solved the issue?
Yes refer to this comment [#1603 (comment)](https://github.com/spicetify/spicetify-cli/issues/1603#issuecomment-1107513548), but all you need to do is clear the backup and then uninstall spotify and reinstall it and then apply the theme it should work perfectly
