### ISSUE TITLE
Colors do not change again after updating Spicetify to 2.9.6

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#218]
Same issue as the closed #199

OS: macOS 12.3.1
Spotify: 1.1.83.956
Spicetify: 2.9.6
Dribbblish: 4.1.4-239033a

**Comment by JulienMaille** [comment]
Can you try in both light and dark modes?

**Comment by ps13g** [comment]
Yep I just tested it in Light and Dark mode and the issue is still there

**Comment by JulienMaille** [comment]
@ps13g can you tried this test build? https://github.com/JulienMaille/dribbblish-dynamic-theme/suites/6236227072/artifacts/221409635
