### ISSUE TITLE
Left Sidebar refuses to scroll down

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#219]
**Describe the bug**
The Left Sidebar refuses to scroll down for playlists.
**To Reproduce**
1. Open Spotify

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `macOS v12.3.1`
  Spotify: `1.1.83.956`
  Spicetify: `2.9.6`
  Dribbblish: `Beta-9ea343f`

  **Extensions**
  - dribbblish-dynamic.js
  - fullAppDisplay.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "Beta",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none-padding",
      "playbarShadow": false,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": false,
      "showGenreInfoInPlaybar": false,
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#409fa5",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "dark",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
Please see my question in #187

**Comment by ps13g** [comment]
Here is what my patch section looks like 
`[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.83.956.gbe7ea9a7
with    = 2.9.7`

**Comment by ps13g** [comment]
> Here is what my patch section looks like
> 
> -e [Patch] xpui.js_find_8008 = ,(\w+=)32, xpui.js_repl_8008 = ,${1}58,

I had just updated to version 4.2.0 for Dribblish and it still does not work

**Comment by JulienMaille** [comment]
Do you get no scroll at all? Or can you just no reach the bottom?

**Comment by ps13g** [comment]
I can not reach the bottom at all

**Comment by JulienMaille** [comment]
Can you share a gif?

**Comment by ps13g** [comment]
https://imgur.com/a/GpfTdmd
It just stops at the bottom icon and won't go farther and the only other extension that I have is the fullappdisplay
