### ISSUE TITLE
No SpotifyNoPremium option

### ISSUE THREAD

**Issue by Jabari-z** [JulienMaille/dribbblish-dynamic-theme#222]
**Describe the bug**

No SpotifyNoPremium option

**To Reproduce**
1. open the setting
2. main setting

**Screenshots**

![Xnip2022-04-25_10-10-11](https://user-images.githubusercontent.com/49381087/165009329-d9334f3a-ee22-4847-9f63-6dcf31208679.jpg)

**Desktop Setup**
OS: Osx v12.3.1
Spotify: v1.1.83.956
Spicetify: v2.9.7
Dribbblish: v4.2.0-69f283c

**Logs**

```console
[paste logs here]
```

**Comment by Davoleo** [comment]
it's been disabled here (https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/ea97d6924590c748ed8f0dffe9a1d1ce69d507e0) for the moment due to this issue -> #213
