### ISSUE TITLE
Play Button Not Displaying Properly

### ISSUE THREAD

**Issue by nigelonius** [JulienMaille/dribbblish-dynamic-theme#223]
**Describe the bug**

**To Reproduce**
1. 

**Screenshots**

![Screenshot 2022-04-28 091404](https://user-images.githubusercontent.com/87260000/165698087-974c05ec-9537-4b3c-8f80-0274813448f6.png)
![Screenshot 2022-04-28 091301](https://user-images.githubusercontent.com/87260000/165698152-773e8f4a-02dc-4d34-94bc-3eabe157e7e4.png)

**Logs**

```console
[paste logs here]
```

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.22598`
  Spotify: `v1.1.83.956`
  Spicetify: `v2.9.7`
  Dribbblish: `v4.2.0-69f283c`

  **Extensions**
  - fluent.js
  - dribbblish-dynamic.js
  - extension.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.2.0",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none",
      "playbarShadow": true,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "light",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
Can you tried to remove fluent.js from your config?

**Comment by nigelonius** [comment]
> Can you try to remove fluent.js from your config?

I did and it's still the same
