### ISSUE TITLE
Elements are not displayed correctly when Left Sidebar is dragged to an extent

### ISSUE THREAD

**Issue by kyrie25** [JulienMaille/dribbblish-dynamic-theme#224]
**Describe the bug**

Elements on playlists are not displayed correctly if Left Sidebar is dragged completely to the left, would return to normal behavior if Left Sidebar is dragged rightward to an extent
**To Reproduce**
1. Apply theme
2. Open Spotify
3. Open a playlist
4. Drag Left Sidebar to the left completely
5. Elements are not displayed correctly

**Screenshots**

- Left Sidebar dragged to the right to a certain extent, elements displaying normally
![image](https://user-images.githubusercontent.com/77577746/165768550-f0fe8057-b236-4339-9f18-d1fe58ff707a.png)
- Left Sidebar dragged completely to the left, elements display abnormalities starts appearing, most notably album title, artist names, playlist title are affected
![image](https://user-images.githubusercontent.com/77577746/165768986-96a16fda-7f8d-4f46-8a42-5769559b4306.png)
- DevTools locating one of the elements (album title) affected
![image](https://user-images.githubusercontent.com/77577746/165769365-b0d51d9f-7385-4ede-96bc-ddfa946823df.png)

**Logs**

![image](https://user-images.githubusercontent.com/77577746/165769842-bce88eb0-1197-4c5f-bb7e-f0c61894b1cd.png)

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.22000`
  Spotify: `v1.1.84.716`
  Spicetify: `v2.9.7`
  Dribbblish: `v4.2.0-69f283c`

  **Extensions**
  - dribbblish-dynamic.js
  - extension.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.2.0",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": true,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none-padding",
      "playbarShadow": true,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "colorthief",
      "colorOverride": "#1ed760",
      "colorSelectionMode": "default",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "system",
      "darkModeOnTime": "18:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by JulienMaille** [comment]
Theme is broken with latest Spotify update

**Comment by kyrie25** [comment]
Yeah I've taken that for granted every Spotify update now, but only decided to make this issue because it might be overlooked on the nearest patch.

**Comment by trey7658** [comment]
I have that issue.

**Comment by Sayykii** [comment]
I have the same issue.

**Comment by khaledmoayad** [comment]
how do i make them circles like in the previews in the original post
