### ISSUE TITLE
multible search boxes

### ISSUE THREAD

**Issue by JackPlaysGames0510** [JulienMaille/dribbblish-dynamic-theme#226]
**Describe the bug**

**To Reproduce**
1.

**Screenshots**

**Desktop Setup**
- Operating System: 
- Spotify: 
- Spicetify: 
- Dribbblish: 

**Logs**

```console
[paste logs here]
```

**Comment by ps13g** [comment]
Can you send what Spicetify and Spotify version you are on? This can be fixed when updating to the latest version of Spicetify

**Comment by JulienMaille** [comment]
Yeah please do so

**Comment by eshuaiii** [comment]
Sorry to reopen the thread; I have the same issue.

Spicetify 2.9.8 (latest version as of writing this), Dribbblish-Dynamic 4.2.1.
Here's a screenshot:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/63947753/167271074-191347ea-f4af-41e6-8269-dad7096cedd3.png">
Also triple settings for some settings:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/63947753/167271084-c266893b-1fd2-453e-918a-9b606bb102a0.png">

This is after a fresh install of Spotify, Spicetify, and the theme.

OS: Windows v10.0.22000
Spotify: v1.1.84.716
Spicetify: v2.9.8
Dribbblish: v4.2.1-d03d89b
