### ISSUE TITLE
CSS issue - bug

### ISSUE THREAD

**Issue by trey7658** [JulienMaille/dribbblish-dynamic-theme#228]
**Describe the bug**

My Spotify text is not showing properly on the sidebar
**To Reproduce**
1. Open spotify

**Screenshots**
Dark mode:
![image](https://user-images.githubusercontent.com/47907719/166837233-30b739c8-0683-41cb-9b13-440ee6505867.png)
Light mode:
![image](https://user-images.githubusercontent.com/47907719/166837493-c008ef22-ca09-447d-bdf1-1815790c0c7e.png)

**Logs**

I dont think that logs are necessary here but i will add them if needed

---

<details>
  <summary>Info for Contributors</summary>

  **Versions**
  OS: `Windows v10.0.22000`
  Spotify: `v1.1.84.716`
  Spicetify: `v2.9.8`
  Dribbblish: `v4.2.0-69f283c`

  **Extensions**
  - dribbblish-dynamic.js
  - extension.js

  **Settings**
  ```json
  {
      "EXPORTED_WITH": "4.2.0",
      "showLoadingScreen": true,
      "openSettingsInfo": true,
      "showSearchBox": true,
      "rightBigCover": true,
      "roundSidebarIcons": false,
      "sidebarHoverAnimation": true,
      "sidebarGapLeft": 5,
      "sidebarGapRight": 32,
      "winTopBar": "none",
      "playbarShadow": false,
      "playbarTransition": true,
      "playerControlsStyle": "dribbblish",
      "showAlbumInfoInPlaybar": true,
      "showGenreInfoInPlaybar": false,
      "fadeDuration": 0.5,
      "customCss": "",
      "colorSelectionAlgorithm": "vibrant",
      "colorOverride": "#1569ef",
      "colorSelectionMode": "luminance",
      "lightModeLuminance": 0.6,
      "darkModeLuminance": 0.2,
      "theme": "system",
      "darkModeOnTime": "20:00",
      "darkModeOffTime": "06:00",
      "bgTheme": "bw"
  }
  ```
</details>

**Comment by Hakosuka0** [comment]
#224 Duplicate

**Comment by trey7658** [comment]
Thanks!
