### ISSUE TITLE
Update v4.2.0/v4.2.1 cannot be installed

### ISSUE THREAD

**Issue by vvirtues** [JulienMaille/dribbblish-dynamic-theme#229]
**Describe the bug**

cmd recognizes incorrect command, causing update to terminate
**To Reproduce**
1. Have previous update
2. Try to update using powershell script
3. Get this

**Screenshots**

![image](https://user-images.githubusercontent.com/81705406/167138054-32fe39a5-efc1-46b2-8c5a-1164e6ccfb4d.png)

**Desktop Setup**
OS: Windows v10.0.22000 (Windows 11 but shows as 10 for some reason idk)
Spotify: v1.1.84.716
Spicetify: v2.9.8
Dribbblish: v4.1.4-239033a

**Logs**
Not needed

```console
[N/A]
```

**Comment by JulienMaille** [comment]
What happens if you manually call `spicetify config color_scheme base`?

**Comment by vvirtues** [comment]
> What happens if you manually call `spicetify config color_scheme base`?

What should I set it as?

**Comment by vvirtues** [comment]
EDIT: Same thing for v4.2.1 as well

**Comment by vvirtues** [comment]
nvm by installing `lsd` using scoop seems to work, idek what it is lmao
