### ISSUE TITLE
cannot find symbol for Custom app React Element

### ISSUE THREAD

**Issue by kuyajoseph** [JulienMaille/dribbblish-dynamic-theme#235]
Description:
I have the latest version of both spotify and spicetify, but the installation won't work in powershell.

1. Follow the installation process

Screenshots:
![image](https://user-images.githubusercontent.com/22106809/168884251-2c38ba8c-b60e-404b-9f6c-95a19be9fc22.png)

Setup:
OS - Windows 10
Spotify: 1.1.85
Spicetify: 2.9.8
Dribbblish: Latest (just updated)

**Comment by Davoleo** [comment]
that's a Spicetify issue (Ref: https://github.com/spicetify/spicetify-cli/issues/1660)
