### ISSUE TITLE
dribbblish-dynamic.js not installed correctly

### ISSUE THREAD

**Issue by Kayqubad** [JulienMaille/dribbblish-dynamic-theme#236]
I followed to automatic and manual install, I reinstalled the theme, spicetify and spotify a bunch of times.

Step to reproduce:
Follow the install procedure

![image](https://user-images.githubusercontent.com/52562895/168975384-2eda3dae-cfc8-4ae7-8f02-e889e5b64d8e.png)

**Comment by sabieber** [comment]
Having the same issue here (on macOS)
