### ISSUE TITLE
With the new Spotify update the albums and playlist pages look really bad

### ISSUE THREAD

**Issue by ferNayeon** [JulienMaille/dribbblish-dynamic-theme#244]
![imagen](https://github.com/user-attachments/assets/5161730a-297e-418e-888e-237d6d6dd85f)

This is my fav theme at the moment so, how can this be fixed?

**Comment by JulienMaille** [comment]
Is it broken in the original Dribbblish them as well?

**Comment by ferNayeon** [comment]
thank you so much! the 2023 mix really made me love this album even more that I already did

And yes, this also happens with the original Dribblish them. I'll give you more details:

Last friday Spotify launched version 1.2.49; which had one of the changes being that playlists and albums pages have these gradient colors in the top. Before the friday, the Dribblish theme (the original and this one, the Dynamic one) had all of the playlists and albums pages all black, as you already obviously know because it is your code hahah

Now spotify did this arbitrary change and a lot of themes now look really weird. But this one was my fav one at the moment so I reaaaally want this fixed. Thanks btw!

**Comment by ferNayeon** [comment]
Update: I installed and old spotify version, specifically the one before the most recent, and it's perfect and beautiful again.  

![imagen](https://github.com/user-attachments/assets/632f6c51-4a37-4e51-91f6-15a0fd80e0bc)

Now I don't have a problem with the code staying just the way it is hahah, but if you will change it, please make it look awesome like in this version!

**Comment by JulienMaille** [comment]
I'm on 1.2.49 and can't reproduce your issue:
```
Spotify  pour Windows (64 bits)
1.2.49.439.gfae492c7
Spicetify v2.38.4
xpui_2024-10-21_1729514985745_fae492c
cef_129.0.11+g57354b8+chromium-129.0.6668.90
Runtime: Chrome
Build System: Bazel
```

**Comment by ferNayeon** [comment]
hey, just updated spotify cause I saw you updated the theme and everything's perfect 🙏🏼

Just one more thing:

The "base" theme and the "NoBackground" look the same to me, as the NoBackground appears

**Comment by ferNayeon** [comment]
Nice, thank you so much! Now it's literally 100% perfect hahah, wouldn't change a thing. I'm closing this thread!
