### ISSUE TITLE
Can we decrease brightness of sidebar colour?

### ISSUE THREAD

**Issue by b4nn** [JulienMaille/dribbblish-dynamic-theme#245]
Hi @JulienMaille,

Thank you for creating this theme. It looks so much better than default one!

I don't know much about theming but I'd like to make a amall tweak for myself. Could you advise which files I should edit? Specifically I'd like to change the left sidebar background colours to be darker. This is personal preference but if you'd like to consider this for your relase it would help with text accessibility (color contrast). I installed spicetify via powershell. 

Best,
Emil

**Comment by JulienMaille** [comment]
Hello Emil, you wanna darken the sidebar color
https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/1b018f0776e540c5838ffb1a35ab60e01e0a9b5e/dribbblish-dynamic.js#L412
Something like `setRootColor("sidebar", lightenDarkenColor(darkerColHex,-40));`
