### ISSUE TITLE
Can we go back to the "now playing" background being in a dark solid color?

### ISSUE THREAD

**Issue by ferNayeon** [JulienMaille/dribbblish-dynamic-theme#246]
![image](https://github.com/user-attachments/assets/df74d5ca-2139-40b1-a35a-4f8991b33625)

It looked so, so good

**Comment by ferNayeon** [comment]
right now it looks like this:

![image](https://github.com/user-attachments/assets/5ef6ca9f-5e0c-4849-a2dd-c3a001868552)

And sometimes you can't really read the title of the song

**Comment by JulienMaille** [comment]
This is what I get with `Base` settings
![image](https://github.com/user-attachments/assets/5ceb94fa-6d38-4db3-bfa5-98c7f318122d)
and with `NoBkgrnd`
![image](https://github.com/user-attachments/assets/70d0c512-b9c3-4b1d-bfd2-cc8127273fe1)

**Comment by ferNayeon** [comment]
loved that you used the same album hahaha

But yeah thats weird. Any ideas on why this is like that? Can i do smth to fix it in my spotify?

**Comment by JulienMaille** [comment]
Please show a complete snapshot, I don't understand how it looks on your side

**Comment by ferNayeon** [comment]
Yeah sure:

![image](https://github.com/user-attachments/assets/8c8ce3a9-f16e-4e3a-b829-5a1ec3c3d70a)

![image](https://github.com/user-attachments/assets/c012e3e9-b387-4842-a737-1c02cbbcf9fe)

![image](https://github.com/user-attachments/assets/cc081903-bcc4-4f2b-8e1e-2273da4b6a33)

And my version:

![image](https://github.com/user-attachments/assets/8bd4446f-e26d-49fb-91c0-117410ab17b2)

**Comment by JulienMaille** [comment]
Maybe try to switch to another theme from the marketplace and back to this one
