### ISSUE TITLE
[COMPLAINT] Color Picking has changed and become worse | SOLUTION

### ISSUE THREAD

**Issue by Dr-DaNk** [JulienMaille/dribbblish-dynamic-theme#25]
Ever since updating dribbblish-dynamic, the backgrounds of albums that I played in previous versions were very different now. I figured out the issue is simply that the quality of 12 at dribbblish-dynamic.js:251 is way too high. Bringing the value to the default 5 as noted in the Vibrant.js github caused no performance changes and returned the true vibrant colors as my background.

**Comment by JulienMaille** [comment]
Interesting feedback, can you test the value of 5 for a few days and confirm it gives nice results?
FYI, I'm currently not working on the theme (not event using it), waiting for a spicetify fix compatible with latest spotify.

**Comment by Dr-DaNk** [comment]
Most of the time, the colors are more accurate. Sometimes 12 does provide a color that I think would match better but very rarely. I added a bit of code to show all of the options for both 5 and 12 in the console output for every song. Overall, I think 5 does a better job. Most of the time, the colors are actually almost exactly the same, but I don't see why 5 is a bad option as it doesn't make any notable drop in performance and is almost always more accurate.
