### ISSUE TITLE
Can't read the sidebar at all when an album with a white cover is played in dark mode

### ISSUE THREAD

**Issue by kulaid** [JulienMaille/dribbblish-dynamic-theme#28]
Use dark mode
Play an album that makes the sidebar completely white, example: Call Me If You Get Lost by Tyler, The Creator

![image](https://user-images.githubusercontent.com/87280154/128264658-dc2abdc4-99e3-497b-857d-2f4cadc1939d.png)

 - OS: Windows 10
 - Version 1.7

**Comment by JulienMaille** [comment]
Thank, will look into this when back from holidays. Can you check logs for errors,just in case?

**Comment by kulaid** [comment]
![image](https://user-images.githubusercontent.com/87280154/128379348-7f94454b-f347-4cac-a93c-25a44fc377a7.png)
Here they are, also I'm using the patch to allow spicetify to work on the newest spotify version but this also happens in 1.1.62

**Comment by JulienMaille** [comment]
the patch doesn't fix everything, there's nothing I can do in the meantime

**Comment by ps13g** [comment]
An immediate workaround is using these two commands which should change the text of the color to black. 

`spicetify config color_scheme dark`

`spicetify apply`

**Comment by Powlcopter** [comment]
I created a fix for this: https://gist.github.com/Powlcopter/ae73115a4251245bfca26642de2d78e9

It just changes the color of the Text and the symbols in the sidebar to a dark grey when the brightness of the main sidebar color is below a certain threshold, and changes it back to white when it's under the threshold.

The change in line 71 probably makes a bunch of things in light mode look weird but I couldn't get around to fix that. (everything works fine in dark mode)

In order to install this, just replace the dribbblish-dynamic.js file in %userprofile%\.spicetify\Extensions with the file from the link above and run `spicetify apply` (make sure to back up the original first, in case my version breaks something for you.)

**Comment by JulienMaille** [comment]
I don't have your problem when trying with the same song:
![image](https://user-images.githubusercontent.com/182520/133887599-a4530d9f-df4d-49e8-9642-03d295246e94.png)

**Comment by Powlcopter** [comment]
> I don't have your problem when trying with the same song:

[This commit](https://github.com/JulienMaille/dribbblish-dynamic-theme/commit/28d977631f8d240074b9a6a0852e714a751a7f87) is what changed that behavior, if you switch that back to 12, you actually get the really bright color from that album. I would assume that even with 5 in that setting, it would still result in bright colors for some albums.

**Comment by kulaid** [comment]
> I don't have your problem when trying with the same song:
> ![image](https://user-images.githubusercontent.com/182520/133887599-a4530d9f-df4d-49e8-9642-03d295246e94.png)

Does it also work in dark mode? Because it only happens to me in dark mode not white mode.

**Comment by JulienMaille** [comment]
Do you have the latest version of my theme?

**Comment by JulienMaille** [comment]
> I would assume that even with 5 in that setting, it would still result in bright colors for some albums.
Can you share some examples?

**Comment by Powlcopter** [comment]
> Can you share some examples?
Here you go:
![image](https://user-images.githubusercontent.com/30203227/133897135-bdf9b2e1-08c4-45ab-9e21-dce8478913ca.png)
These are technically not white but very hard to see anyway:
![image](https://user-images.githubusercontent.com/30203227/133897214-3d1cf5ed-67dd-4f48-9398-befa030c4089.png)
![image](https://user-images.githubusercontent.com/30203227/133897255-2db06266-9ce5-4d1a-bed4-27a5447cdebb.png)
All of these are taken with the default setting of 5 colors per swatch
I believe the reason why using only 5 colors makes the colors darker is that it very often fails to find a Vibrant or LightVibrant color and then instead uses a DarkVibrant or Muted, wich often happen to be darker (for example on the TTC album from the original issue, it uses the Muted)
Also, Vibrant.js is not completely consistent across devices, wich could also explain some of the smaller differences in this tread

**Comment by JulienMaille** [comment]
I pushed a fix, in the mean time it seems spotify update broke the way cover updates are detected. Can you give it a look?
