### ISSUE TITLE
[BUG] Song Duration and Timestamp tooltip is blank and stuck

### ISSUE THREAD

**Issue by Davoleo** [JulienMaille/dribbblish-dynamic-theme#29]
**Describe the bug**
As you can see from the screenshot below the tooltip that should show the total duration of a track and it's current timestamp, is shown blank, this happens both in dark and light mode
Furthermore the tooltip is stuck at the beginning of the progress bar and doesn't move while the song plays

**To Reproduce**
- Play a song and notice the tooltip behaviour

**Screenshots**
![image](https://user-images.githubusercontent.com/24458276/128499481-57411ce9-6ae0-4a3d-a9c5-3f84c3d4faa8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Spotify Version: 1.1.65.643.g2d707698-a
 - Dribbblish Version: 1.7
 - I'm using the new spicetify patch that allows it to work with the latest spotify version I don't know if this will help but I'll put it here in case you need to know

**Logs**
The console shows the following errors:
![image](https://user-images.githubusercontent.com/24458276/128499984-aec01c77-358b-42fe-ba2c-2e3119345f91.png)

**Comment by Davoleo** [comment]
ok nevermind seems like this is an issue with the latest spicetify patch as well, ref: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-893530858

**Comment by Davoleo** [comment]
ok for some reason, even after installing the latest patch, this problem still persist are you able to reproduce it as well?

**Comment by JulienMaille** [comment]
even with latest patch, spicetify is broken
