### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#3]
Do you guys have a more concrete way on how to install this theme? Currently, I'm running the Dribbblish that was made by @khanhas and it works smoothly. But coming to the installation of Dribbblish Dynamic on MacOS it runs into the (23) Failed writing body error code.

**Comment by JulienMaille** [comment]
How did you solve it?

**Comment by ps13g** [comment]
> How did you solve it?

I had to reinstall the entire .zip file and I had to go in and manually copy and paste the extensions required for the theme.
