### ISSUE TITLE
green

### ISSUE THREAD

**Issue by cr1ptik** [JulienMaille/dribbblish-dynamic-theme#30]
![image](https://user-images.githubusercontent.com/68492220/128927196-45118d68-feb8-4e40-9096-8c6d3b259bc3.png)
green

**Comment by Davoleo** [comment]
_green_ (～￣▽￣)～

**Comment by SpectrixDev** [comment]
I actually have this problem lol, whole thing is just green. How do I fix it?

**Comment by cr1ptik** [comment]
Idk he closed it and didn't help at all
