### ISSUE TITLE
[BUG] Old Versions of the theme are kept inside spicetify-cli/Themes

### ISSUE THREAD

**Issue by Davoleo** [JulienMaille/dribbblish-dynamic-theme#31]
**Describe the bug**
The Title Basically says it all, when updating the theme old versions are kept in the Theme folder, it would be nice if they were removed
While they can serve as restore points, most of the times more than one restore point isn't really needed

**To Reproduce**
- open spicetify-cli/Themes
- See all the old versions of the theme

**Screenshots**
![image](https://user-images.githubusercontent.com/24458276/130035597-2c2725b8-22dc-41c3-a5d6-8a09cf81d1f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

I don't think logs are needed, but if they are please tell me and I'll provide them

**Comment by JulienMaille** [comment]
not a bug
