### ISSUE TITLE
[BUG]The color defaults to green, error in console.

### ISSUE THREAD

**Issue by huhridge** [JulienMaille/dribbblish-dynamic-theme#35]
The color goes to default and a weird pink.

**To Reproduce**
Install spicetify-2.6.5, and this theme.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67046436/134551528-c9a805c5-0440-4990-b7ee-89662c3c1acf.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Spicetify Version : 2.6.5

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
<img width="751" alt="image" src="https://user-images.githubusercontent.com/67046436/134551808-01680c0f-223e-45cc-be1e-36620cdcb02f.png">

```

**Comment by huhridge** [comment]
The logs weren't showing:
dribbblish-dynamic.js:178 Uncaught ReferenceError: DribbblishShared is not defined
    at dribbblish-dynamic.js:178
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1033981
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by JulienMaille** [comment]
How did you install the theme?
I think you have a missing .js file

**Comment by huhridge** [comment]
I added all 3 .js files to the config, dribbblish.js|dribbblish-dynamic.js|Vibrant.min.js

**Comment by JulienMaille** [comment]
have you copied those 3 files in the `Extensions` folder?

**Comment by huhridge** [comment]
Yes, I have.

**Comment by JulienMaille** [comment]
`DribbblishShared` is defined in dribbblish.js, check that this file is loaded from the dev console
![image](https://user-images.githubusercontent.com/182520/134763775-7ce1dd86-992c-4b3e-9826-afe22e071579.png)

**Comment by JulienMaille** [comment]
I've read on discord that they recommend to completely remove spicetify-cli and .spicetify folder, then reinstall

**Comment by huhridge** [comment]
I reinstalled spicetify, and even Spotify, but still same, and dribbblish.js is shown in the sources tab.

**Comment by JulienMaille** [comment]
Have you tried installing this theme with the command line given in the readme?

**Comment by huhridge** [comment]
The command just stops, but I think that's just because I use brew spicetify,
<img width="570" alt="image" src="https://user-images.githubusercontent.com/67046436/134819592-e046d9c3-7e52-42df-b71e-c38e9e7cc212.png">

**Comment by JulienMaille** [comment]
I would suggest you join the discord and ask other macOS users: https://discord.gg/RVDYmKSy

**Comment by huhridge** [comment]
I just tried the dribbblish theme, and that works, is there any reason for the dribbblish and the dynamic.js to be separate?

**Comment by JulienMaille** [comment]
The reason is that dribbblish.js is from @khanhas and dribbblish-dynamic.js is from me.

**Comment by huhridge** [comment]
I just found the solution, I didn't know that the order of extensions matter, I must have done dynamic then original dribbblish.js, I switched them and its working perfectly fine, sorry to bother you
