### ISSUE TITLE
[BUG] The album name still duplicates

### ISSUE THREAD

**Issue by mikasodc** [JulienMaille/dribbblish-dynamic-theme#43]
The album names start adding up on the now playing.

Steps to reproduce the behavior: Simply skip the music...

![image](https://user-images.githubusercontent.com/83371344/135167928-10256498-ab22-4a4f-9bed-500270ca47fe.png)

 - OS: Windows
 - Version 1.9

![image](https://user-images.githubusercontent.com/83371344/135168094-de146377-9c9c-4318-a9dc-daedfc605bc9.png)

**Comment by JulienMaille** [comment]
duplicate of #37
