### ISSUE TITLE
Artist Banners look zoomed-in

### ISSUE THREAD

**Issue by Davoleo** [JulienMaille/dribbblish-dynamic-theme#47]
This is not really a bug nor a direct feature request, I'll just drop it here as discussion on the matter.

The cause of the banner looking zoomed-in can be traced back to:
- Artists having a large banner photo because Spotify's original ratio is different
- Banner height based on the height of the whole window instead of the actual visible space cuts a bit from the top and from the bottom of the banner increasing the visual effect of the photo being zoomed in.

I don't know a good solution for this but I thought I would bring it up in case someone knows one 🤔 

Inspected size of the div that hosts the artist banner:
![Immagine 2021-09-30 150630](https://user-images.githubusercontent.com/24458276/135461128-77cf257c-f963-4bff-9e08-a835dd9b11dc.png)
Actual artist banner that is hosted on Spotify's CDN
![AKG_BANNER](https://i.scdn.co/image/ab6761860000101621c4e78c98071489068513be)
 
Another Example:
![image](https://user-images.githubusercontent.com/24458276/135461707-1534b4d0-b32c-4098-8927-fcc1b54b0bf2.png)
![THE_ORAL_CIGARETTES_BANNER](https://i.scdn.co/image/ab67618600001016cf2e12fdb911c4b858b8a8a2)

**Comment by JulienMaille** [comment]
I think that's already the best solution, you have to fit the smallest side, in that case the height. Otherwise you can't fill in the screen.
