### ISSUE TITLE
New color scheme

### ISSUE THREAD

**Issue by WelkinBunbury** [JulienMaille/dribbblish-dynamic-theme#53]
![image](https://user-images.githubusercontent.com/33565456/136308458-59329c57-bb37-4432-b55e-c653691cf9e4.png)
Some colors are making the ui elements (repeat and shuffle button) less visible which makes the whole ux less polished.

Solution : choose a more pronounced color scheme which looks good with both dark and light theme or choose different saturation for same hue for dark and light theme

**One more big problem is**
That it always chooses the same color from a particular song album art and because of that if we dont like the color it chooses we have no choice but to stick with it.
The solution can be that either
Dont let it pick boring colors
Or
Let it choose diffrent type of colors from same album art.. Like first time it chooses a color that is largely present next time it takes a color which is not present in huge amount in the album art next time a complementary color etc

**Comment by Pomis** [comment]
@SendNukez omg just wanted to create an issue about picking different colors when on dark and light mode =) please, add it

**Comment by JulienMaille** [comment]
@SendNukez can this be closed?
