### ISSUE TITLE
[BUG] Playlist name dissapears

### ISSUE THREAD

**Issue by brenmadeit** [JulienMaille/dribbblish-dynamic-theme#58]
**Describe the bug**
Playlist name dissapears

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/83563626/136557948-759758f8-9104-45a4-a93b-4d6c6377c655.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home Single Language
 - Version [e.g. 22] 21H1 / 19043.1263
 
**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.
![image](https://user-images.githubusercontent.com/83563626/136558209-3a7f4b23-9057-469c-b58a-b48e8c754ac6.png)

```console
(Please paste here console logs or attach a screenshot)
```

**Comment by SendNukez** [comment]
What was / is  the full name of the playlist?

**Comment by brenmadeit** [comment]
ah I fixed it by uninstalling then reinstalling
