### ISSUE TITLE
default options

### ISSUE THREAD

**Issue by JulienMaille** [JulienMaille/dribbblish-dynamic-theme#59]
I wasn't able to test all recent commits until today, a few remarks for @SendNukez (if you want to chat on discord instead of using issues, let me know)
- first: thanks for all you recent contributions, giving a second life to this theme. I must admit that the recent spotify updates, breaking all the css, had decreased my motivation to work on dribbblish-dynamic
- i'd prefer to have round icons as the default setting, currently the squarish option doesn't work well when overing on our friends icons as well as the user account profile picture
At least fix the overlay
```css
.main-buddyFeed-avatarContainer .main-buddyFeed-overlay {
    border-radius: FIXME;
}
```
- system dark color: I believe spotify broke that for good and I'm not sure we can fix it. js/css will always return that the system is set in dark mode, even when it's not, at least under Windows https://github.com/khanhas/spicetify-cli/issues/1095
We could probably remove that option

- toggle switches have a weird look since d3cf6c2853f4db9fa36a603fd152002c29eef34d in light mode the round button is barely visible, why do you think?

**Comment by SendNukez** [comment]
And if we remove the System theme, which theme should be default?

**Comment by JulienMaille** [comment]
> So even if the icons worked better when square you'd prefer them to be round?

Na you can keep default to square 

Regarding default theme, either we set light/dark depending on the time of the day or default to dark (which is the default spotify look) What's your take?

**Comment by SendNukez** [comment]
Actually the Light / Dark depending on time of day is kinda cool, but we'll probably just make it an option you can select insted of default, because it's probably going to be annoying for some people. I think I'll just make dark the default option and add a "Based on Time" option wich will reveal more options when selected to change the times that it is dark, and times it will be light. Basically like windows night light.
![image](https://user-images.githubusercontent.com/29760988/136678492-a8dd981a-5935-418f-a789-35bc65af1fb4.png)

**Comment by SendNukez** [comment]
I'll prob also make a config option `Theme > Color` wich could be set to `Dynamic` (Default) or `Static` where if it was static you could set a static color instead of being dynamic.

**Comment by JulienMaille** [comment]
Great job, I will test this and report

**Comment by JulienMaille** [comment]
Based on Time works well 👍

**Comment by SendNukez** [comment]
@JulienMaille I completely forgot to tell you my Discord. It's `Send_Nukez#4501`. I'm a "bit" forgetful sometimes lol
