### ISSUE TITLE
Install.sh

### ISSUE THREAD

**Issue by Ramdonx** [JulienMaille/dribbblish-dynamic-theme#6]
The Install.sh script downloads an old version of the code.
I noticed it for the last modification of the dribbblish-dynamic.js file, the version downloaded by the script, it does not have this modification.

Pd: The last modification of dribbblish-dynamic.js does not solve the problem.

**Comment by JulienMaille** [comment]
The script downloads the latest release, not the latest committed code

**Comment by Ramdonx** [comment]
I see
