### ISSUE TITLE
Enhancement Request, player bar location

### ISSUE THREAD

**Issue by agwosdz** [JulienMaille/dribbblish-dynamic-theme#62]
Hi!

Excellent work on the theme, my favorite. Every time I update my theme, I have to make adjustments to the user.css for the location of the player bar; I truly enjoy the location in the middle.
![image](https://user-images.githubusercontent.com/24953190/136667432-fb756a82-266c-462e-b6c0-41c8171ea1a1.png)

For that, I change the  /** Rearrange player bar */ section in user.css to:

/** Rearrange player bar */
.main-nowPlayingBar-left {
    order: 0;
    flex: 1;
    width: auto;
    min-width: 0 !important;
}

.main-nowPlayingBar-center {
    order: 1;
    flex: 1;
    width: auto;
    min-width: unset !important;
}

.main-nowPlayingBar-right {
    order: 2;
    flex: 1;
    width: auto;
    min-width: unset !important;
}

.main-nowPlayingWidget-nowPlaying {
    justify-content: left;
    padding-left: 20px;
}

.player-controls {
    justify-content: center;
    flex-direction: row;
}

.main-playPauseButton-button {
    background-color: transparent;
}

.main-playPauseButton-button svg {
    width: 32px !important;
    height: 32px !important;
    color: var(--spice-button);
}

Would it be possible to add this as an option in the Main Config Options Menu, maybe as a toggle between original and middle?

Thank you,

Alex

**Comment by SendNukez** [comment]
This will be in the next Release. Thank you for your Suggestion!
