### ISSUE TITLE
[BUG] New update to dynamic.js and user.css breaks Spotify entirely

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#67]
**Describe the bug**
Spotify breaks when new dynamic.js user.css files are used

**To Reproduce**

- Open the app

**Screenshots**

![Screen Shot 2021-10-11 at 5 49 09 PM](https://user-images.githubusercontent.com/84423124/136868211-e2769bb4-239d-4a44-b685-9fa790399a78.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Version: 1.1.69.612.gb7409abc

**Comment by alixti** [comment]
Try to re-install Spotify and then apply the theme.

**Comment by sicr0** [comment]
Uh, I guess it still happens, I just didn't managed to trigger it ahah

**Comment by JulienMaille** [comment]
I'm closing this one and re-opening #63
