### ISSUE TITLE
[BUG] Inconsistent width when hovering items in left sidebar

### ISSUE THREAD

**Issue by JulienMaille** [JulienMaille/dribbblish-dynamic-theme#69]
I'm afraid this was introduced with 97eba93
![image](https://user-images.githubusercontent.com/182520/137212455-a8fe0326-fa66-4d3d-a3ad-e95874e79fbe.png)

**Comment by JulienMaille** [comment]
Gone on 1.1.70.610

**Comment by JulienMaille** [comment]
Still broken on latest updates

**Comment by SendNukez** [comment]
Oh, this is because you have some items unsticked, I'll work on fixing this.
