### ISSUE TITLE
The curl command fails to install

### ISSUE THREAD

**Issue by lor1x** [JulienMaille/dribbblish-dynamic-theme#7]
Hi,

Provided curl command for installing the theme fails.
I get this error on terminal:
`DOWNLOADING    https://api.github.com/repos/JulienMaille/dribbblish-dynamic-theme/releases/latest
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
(23) Failed writing body`

I’m using spicetify-cli 2.2.6 with Spotify 1.1.61 on macOS Big Sur 11.4

Could someone help me with this?

**Comment by NanaAY** [comment]
> Hi,
> 
> Provided curl command for installing the theme fails.
> I get this error on terminal:
> `DOWNLOADING https://api.github.com/repos/JulienMaille/dribbblish-dynamic-theme/releases/latest usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]] [-e pattern] [-f file] [--binary-files=value] [--color=when] [--context[=num]] [--directories=action] [--label] [--line-buffered] [--null] [pattern] [file ...] (23) Failed writing body`
> 
> I’m using spicetify-cli 2.2.6 with Spotify 1.1.61 on macOS Big Sur 11.4
> 
> Could someone help me with this?

I keep getting the same error as well

**Comment by JulienMaille** [comment]
Looks like `grep -P` is not supported on recent MacOs.

**Comment by JulienMaille** [comment]
Can you tried updated script?

**Comment by lor1x** [comment]
Hey @JulienMaille

I figured after posting the issue here that later macOS versions don’t support grep -p anymore.

Well I tried to remove it myself and it would just print DOWNLOADING and stop there. 
Same as the updated script, it stops at DOWNLOADING.

This is what it looks like for me:
![Screen Shot 2021-06-15 at 11 56 58](https://user-images.githubusercontent.com/22913459/122033425-ceb82b80-cdd0-11eb-9be1-873419a8c35a.png)

**Comment by JulienMaille** [comment]
I don't have access to a Mac so all I can try is from windows bash, and there it works
![image](https://user-images.githubusercontent.com/182520/122036894-56536980-cdd4-11eb-8bfa-acd2b08c3eb3.png)

**Comment by JulienMaille** [comment]
@lor1x I forced push a version without single quote just in case, can you try it?

**Comment by NanaAY** [comment]
decided to give it one more try and it finally worked. Awesome work @JulienMaille . @lor1x I suggest you try again. <img width="1214" alt="Screen Shot 2021-06-15 at 10 25 54 AM" src="https://user-images.githubusercontent.com/40281300/122037604-40d64380-cdc4-11eb-9876-ba7e84840d57.png">

**Comment by lor1x** [comment]
Unfortunately I tried again and it still stops there. I should add that I used brew to install spicetify-cli.
I tried to manually install it but fails to open color.ini
Maybe something is badly configured that is causing this. I will try to fix it 😅

Thank you for your help guys, glad it works for you @NanaAY
