### ISSUE TITLE
[BUG] Font is weird

### ISSUE THREAD

**Issue by brenmadeit** [JulienMaille/dribbblish-dynamic-theme#70]
**Describe the bug**
The font is weird, the font on liked songs search in preview should be bold like the original dibbblish but its different in mine
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/83563626/137229662-5d3c0166-f735-41f4-93d2-2946cff0ac33.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 19043.1263
 - Version [e.g. 22] 21H1

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

![image](https://user-images.githubusercontent.com/83563626/137229923-b9ce8508-0a81-49e4-a317-f681f431a871.png)

```console

**Comment by SendNukez** [comment]
This is intended as the bold text looks blurry and is inconsistent with the playlist text.

**Comment by brenmadeit** [comment]
> This is intended as the bold text looks blurry and is inconsistent with the playlist text

okay thanks
