### ISSUE TITLE
REQUEST: Just dynamic background

### ISSUE THREAD

**Issue by NanaAY** [JulienMaille/dribbblish-dynamic-theme#8]
Is there a way for me to only have the dynamic translucent background. That is use my own colors for the sidebar, text, player, card etc. Maybe I can edit the css or .js file to achieve this? Thanks in advance.

**Comment by JulienMaille** [comment]
You should edit the .js and comment out the sections performing the `updateColor()`

**Comment by NanaAY** [comment]
Tried that in the dribbblish-dynamic.js but I'm not seeing a difference. Don't know if I'm doing it wrong.

**Comment by JulienMaille** [comment]
Did you ran `spicetify apply` after making changes to the .js?

**Comment by NanaAY** [comment]
> Did you ran `spicetify apply` after making changes to the .js?

Yeah I did

**Comment by NanaAY** [comment]
I ended up editing the css file and changing the colors there

**Comment by Dr-DaNk** [comment]
You might have been doing what I was doing and editing the .js files in the Themes folder instead of the Extensions folder.

**Comment by Macilvoy** [comment]
> You might have been doing what I was doing and editing the .js files in the Themes folder instead of the Extensions folder.

yo, bro!! you saved me, thx!!
