### ISSUE TITLE
Add to spicetify-marketplace

### ISSUE THREAD

**Issue by SendNukez** [JulienMaille/dribbblish-dynamic-theme#82]
We should add this theme to [spicetify-marketplace](https://github.com/CharlieS1103/spicetify-marketplace) when it gets theme support.

What do you think @JulienMaille?

**Comment by CharlieS1103** [comment]
@JulienMaille We do have plans for it, but on the backburner for now as we sort out the prominent base features and iron out bugs with extensions. For themes such as dribblish we would have to find out how to package the theme and the extension for dribblish dynamic together, as well as the handling of assets for themes which have them.

**Comment by JulienMaille** [comment]
@SendNukez With your latest commits, it seems we only need a manifest.json 
```json
{
    "name": "Dribbblish Dynamic",
    "description": "A mod of Dribbblish theme for Spicetify with support for light/dark modes and album art based colors.",
    "preview": "showcase-images/preview.gif",
    "main": "path-to/dribbblish-dynamic.js",
    "readme": "README.md",
    "usercss": "user.css",
    "schemes": "color.ini"
}
```

**Comment by JulienMaille** [comment]
Next step is to stop updating the branch on every commit and trigger it on a release, is that correct @SendNukez ?

**Comment by SendNukez** [comment]
No, the `beta-release` branch is supposed to be updated on every push, the `release` branch will be the stable branch. It doesn't exist right now because there was no release since I updated the actions, we could just create it ourselves but I'd just wait for the next release since the marketplace is not fully ready yet anyways. So we'd have the manifest be an array of two: Stable and Release. This way people who want to test new stuff before it is in any release can use the beta one, and people who just want the theme can use the stable / release version

**Comment by SendNukez** [comment]
I have also now renamed the branches to be more inline with each other

**Comment by JulienMaille** [comment]
done?

**Comment by SendNukez** [comment]
Should be.
