### ISSUE TITLE
Use Webpack

### ISSUE THREAD

**Issue by SendNukez** [JulienMaille/dribbblish-dynamic-theme#83]
Maybe we could use Webpack to compile all our scripts into one. This means we could split the code up a bit into to make it easier to maintain.

Using Webpack would allow us to use libs like [chroma](https://github.com/gka/chroma.js) for the color operations without having to include more js files (like vibrant) for the user to include in the config. And we could even use SCSS to split up the style into components too.

We should be able to add this as an Action on PR and Push.

I know this is a bit of work, but I'd be happy to do it if it means that our codebase gets easier to maintain.

@JulienMaille do you think this is an good idea?

**Comment by danielphan2003** [comment]
I tried out the latest commit on NixOS and everything seems to be working fine :)

Check out https://github.com/danielphan2003/flk/blob/main/pkgs/data/misc/dribbblish-dynamic-theme/default.nix for how to build this on Nix (note: i will update this later)

![image](https://user-images.githubusercontent.com/34669737/139532226-0fdb3a7f-ce74-404b-b1f1-25c7f3879dc6.png)

**Comment by danielphan2003** [comment]
I would love to package this without custom `yarn.lock` file, but I *guess* using `package-lock.json` is good enough, but for now I will update lockfile manually.

**Comment by SendNukez** [comment]
Should be pretty easy to implement, just forgot to do it.

**Comment by SendNukez** [comment]
Done.
