### ISSUE TITLE
How to move play button?

### ISSUE THREAD

**Issue by livepo88** [JulienMaille/dribbblish-dynamic-theme#9]
Hi. Great theme, thank you. I just want to change something for myself, and I can't do it. I want to move the play button in folders so that it is always, for example, 100px from the folder name to the right. The problem is that if I move the button using "margin..." or "top/right" - it always turns out that the name does not shift the button, but overlaps with each other. So I'm clearly doing something wrong. Can you help me please with it...

![123413](https://user-images.githubusercontent.com/12471396/122631225-d9c1d300-d0d2-11eb-990e-3fb494d98287.PNG)

**Comment by JulienMaille** [comment]
Sorry I don't know, try asking on Discord https://discord.gg/wmreGt4VB9
