### ISSUE TITLE
Removing (or the ability to) the extra space in between playlists

### ISSUE THREAD

**Issue by loliloveruwu** [JulienMaille/dribbblish-dynamic-theme#90]
**Is your feature request related to a problem? Please describe.**
not really, just first world problem

**Describe the solution you'd like**
either removing the extra space of nothing between playlists

**Describe alternatives you've considered**
if it even is possible to code, make a new option into the config menu for removing/adding this space

**Additional context**
### base sidepanel and spacing in between 2 playlists
![image](https://user-images.githubusercontent.com/71466044/139538837-fc1a2e57-a1d1-4459-bdbb-65d565c4f269.png)

### proposed, new playlist separation space
![image](https://user-images.githubusercontent.com/71466044/139538904-bb7c7422-b92a-4dc9-9c0b-5cf625eb0cf1.png)

**Comment by SendNukez** [comment]
Will be in the next release, thank you for your suggestion!
