### ISSUE TITLE
[BUG] Color fade duration not working

### ISSUE THREAD

**Issue by Hazzrd** [JulienMaille/dribbblish-dynamic-theme#91]
**Describe the bug**
Color fade not working

**To Reproduce**
skip to the next available song or fade into it (not color fade)

**Screenshots**

https://youtu.be/u2HKXx_bvAI

**Desktop (please complete the following information):**
 - OS: windows 10 home
 - Version 10.0.19043 build 19043

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
vendor~xpui.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2487610)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2489892)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2136447
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2729463)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2753315)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2753094)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2737865)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2736787)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2699243
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699188)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699123)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2737286)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2763699)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2766810)
    at https://xpui.app.spotify.com/xpui.js:1:1031261
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by SendNukez** [comment]
What have you set `Dribbblish Settings > Animations & Transitions > Color Fade Duration` to?

**Comment by Hazzrd** [comment]
> What have you set `Dribbblish Settings > Animations & Transitions > Color Fade Duration` to?

any, whatever time I set it to nothing happens it stays at an instant transition with no fade

**Comment by JulienMaille** [comment]
I can't reproduce that issue.
Can you delete `.spicetify` and `spicetify-cli` folders
Then reinstall Spicetify `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
`

**Comment by Hazzrd** [comment]
> I can't reproduce that issue. Can you delete `.spicetify` and `spicetify-cli` folders Then reinstall Spicetify `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression `

i uninstalled Spotify and spictify re-installed them same issue occurs

**Comment by Hazzrd** [comment]
this only started happening since i updated from 2.6 to 3.0.1

**Comment by JulienMaille** [comment]
You said you uninstalled spicetify but did you deleted the two folders I mentioned?

**Comment by Hazzrd** [comment]
> You said you uninstalled spicetify but did you deleted the two folders I mentioned?

yep fully removed

**Comment by JulienMaille** [comment]
Not reproduced by anyone else. Please make sure you have a clean setup and reopen with additional details if the problem persists.

**Comment by cjghost2000** [comment]
I was getting the same thing, I guess my settings randomly changed make sure [animate controls and elements] is checked you can get here by typing [Adjust the appearance and performance of windows] in the start menu
![image](https://user-images.githubusercontent.com/25965419/147369316-1e0c16a8-fa88-4810-95bd-61d00df4dad1.png)

**Comment by Hazzrd** [comment]
> I was getting the same thing, I guess my settings randomly changed make sure [animate controls and elements] is checked you can get here by typing [Adjust the appearance and performance of windows] in the start menu ![image](https://user-images.githubusercontent.com/25965419/147369316-1e0c16a8-fa88-4810-95bd-61d00df4dad1.png)

Damn, thought I was going crazy lol cant thank you enough!!
