### ISSUE TITLE
Remove Shadow Effect In Playbar

### ISSUE THREAD

**Issue by Dr-DaNk** [JulienMaille/dribbblish-dynamic-theme#92]
Maybe I just completely missed this config option somewhere but is there a way to remove that ugly shadow effect in the playbar to just make it nice and completely black?
![image](https://user-images.githubusercontent.com/39970384/139594191-b7b010c6-9c46-4f88-8a2e-b202f79cdf31.png)

**Comment by Dr-DaNk** [comment]
Also is there a way to expand the text so it fills more of the playbar?

**Comment by SendNukez** [comment]
I'll add the ability to disable the shadow, but I don't really understand what you mean by expanding the text.

**Comment by Dr-DaNk** [comment]
The song info is tiny. Perhaps increase the font and put all the information in one line, keeping the colors the same to differentiate. You could create separate sections for the different parameters, with the text taking up multiple lines in case the information is too long.
<img width="636" alt="Untitled" src="https://user-images.githubusercontent.com/39970384/139598439-17df2151-854d-4848-90da-61d48bbfd04c.png">

**Comment by SendNukez** [comment]
Oh, ok. That should be possible. I'll try to implement this.

**Comment by SendNukez** [comment]
This is turning out to be more difficult than I thought. When playing songs with a lot of artists or long names it looks very bad:
![image](https://user-images.githubusercontent.com/29760988/139874969-891ce92f-bec2-447d-bd74-32a91087b472.png)

The album name can probably just be capped at some length and have `...` at the end of the capped part.
But I don't know what to do for the artists.

For reference, here is how it looks with shorter names:
![image](https://user-images.githubusercontent.com/29760988/139875660-fae37945-c6cb-4fa5-af9e-49e9ed94d62a.png)

**Comment by JulienMaille** [comment]
I don't think we should implement every use suggestion. Spotify already has a scrolling feature to handle long names.
I would be in favor of enlarging the width of the current "now playing" block. But splitting everything in columns has high chances to be both buggy and ugly

**Comment by Dr-DaNk** [comment]
I think if you just expand those elements across more of the play bar, it would look nice. But I think including an option to have less information would be really useful for people who want a more minimalist look

**Comment by Dr-DaNk** [comment]
> I don't think we should implement every user suggestion. Spotify already has a scrolling feature to handle long names.
> 
> I would be in favor of enlarging the width of the current "now playing" block. But splitting everything in columns has high chances to be both buggy and ugly

That's probably the optimal solution, I completely forgot about scrolling!

**Comment by SendNukez** [comment]
I don't quite get what enlarging the width is supposed to do. I've never had a problem with it overflowing.

**Comment by Dr-DaNk** [comment]
Yeah, I have a different use case for my spotify - it takes up a large width of my screen so there's a large amount of real estate unoccupied. It's like 90% blank play bar

**Comment by SendNukez** [comment]
I have [this](https://gist.github.com/SendNukez/a075b9639e845ae196b64aaf774b063f), but when using in combination with `Playbar > Player Controls Style` The center isn't actually in the center because of the way the playbar is rendered. It looks like this:
![image](https://user-images.githubusercontent.com/29760988/139966589-2473421b-8de3-49f5-9662-0df0cadb3aaa.png)
The space is because the playbar is using `justify-content: space-between;` which is correct, but since every one of the three sections is a different width, its not in the center.

Maybe someone wants to try and tackle this, but I'm probably gonna call it for now.

**Comment by JulienMaille** [comment]
@SendNukez time for a release?

**Comment by SendNukez** [comment]
There is just one feature / change I want to make but I want to know how you like it first. I created branch [`glassy-context-menu`](https://github.com/JulienMaille/dribbblish-dynamic-theme/tree/glassy-context-menu) for it.

**Comment by JulienMaille** [comment]
How can I easily test the branch, ie. have webpack package everything together?

**Comment by SendNukez** [comment]
Just run `npm run build` that will create a `dist/` folder with everything you need.

**Comment by SendNukez** [comment]
I could also change the way the [`webpack-test`](https://github.com/JulienMaille/dribbblish-dynamic-theme/actions/workflows/webpack-test.yml) works so that it outputs a zip as artifact so it can be easily downloaded.

**Comment by JulienMaille** [comment]
I don't have npm on my machine

**Comment by SendNukez** [comment]
Oh, ok. I changed the action to upload the builds. But since there is no new commits to trigger it, here is a build: [dist.zip](https://github.com/JulienMaille/dribbblish-dynamic-theme/files/7475593/dist.zip)

**Comment by JulienMaille** [comment]
Thanks a lot, will try it tonight

**Comment by JulienMaille** [comment]
Yeah it's nice, I had worked on frosty context menu in the past but could not come up with something that preserves readable text. Well done

**Comment by JulienMaille** [comment]
Unfortunately it breaks the bookmark popup menu
![image](https://user-images.githubusercontent.com/182520/140408322-c30b436f-57f9-4c10-b51b-82e046a04630.png)

**Comment by SendNukez** [comment]
I have fixed the bookmarks. The album info is actually supposed to be centered, but the image you attached is not looking right. The title is not centered. It's supposed to look like this: 
![image](https://user-images.githubusercontent.com/29760988/140414482-17d1be16-56da-4b95-8a74-3393e6982a88.png)
I'll have to look into that.


It should only be Left aligned when the playbar mode is set to `Spotify` so it looks like this:
![image](https://user-images.githubusercontent.com/29760988/140416016-0bb4d45a-f923-4a0f-83b7-add4b8c640f7.png)

**Comment by Davoleo** [comment]
I can confirm it does look like Julien showed (also on `3.1.0`)

**Comment by SendNukez** [comment]
Yeah, I'll have to look into that. Could you please post your info from `Dribbblish Settings > About > Info`? This could be a new Spotify update I don't have.

**Comment by Davoleo** [comment]
Sure, although it's been about a week since the last spotify update iirc
```
OS: Windows v10.0.19043
Spotify: v1.1.71.560
Spicetify: <= v2.7.2
Dribbblish: v3.1.1-6f7096b
```

**Comment by JulienMaille** [comment]
I can reproduce it but I can't tell if the root cause is a css class which was renamed.
![image](https://user-images.githubusercontent.com/182520/140951788-eb448bd6-608b-4429-8c2b-7fbc32087c4d.png)

**Comment by SendNukez** [comment]
That's odd, you seem to have different classes. It looks like this for me:
![image](https://user-images.githubusercontent.com/29760988/140992543-fed13e3a-763a-4ed6-a681-857ecea12bda.png)

**Comment by SendNukez** [comment]
As the original reason for this issue has been added, we'll continue this bug report in #103
