### ISSUE TITLE
[BUG]  style not applied to the right click menu

### ISSUE THREAD

**Issue by azurefang** [JulienMaille/dribbblish-dynamic-theme#97]
Hey, I  jus install the lastest version and it seems the style is not applied to the right click menu when it's in light mode.  I installed it by shell script.

**Screenshots**
![image](https://user-images.githubusercontent.com/3921442/140007045-c8873edd-42be-4f8d-8462-d8ef7cc020e1.png)

**Desktop (please complete the following information):**
OS: Osx v10.14.6
Spotify: v1.1.71.560
Dribbblish: v3.0.1

console

![image](https://user-images.githubusercontent.com/3921442/140006458-5fdd37ee-3331-4494-b3a7-1b5be1ebf3f3.png)

**Comment by JulienMaille** [comment]
What's your spicetify version? It might be outdated

**Comment by azurefang** [comment]
> What's your spicetify version? It might be outdated

2.7.1, more info:

![image](https://user-images.githubusercontent.com/3921442/140025554-a944ac06-663c-42cf-9859-a10d468e7063.png)

![image](https://user-images.githubusercontent.com/3921442/140025575-86bdee8c-894e-4f4f-a2ff-cfaa83a80cd7.png)

![image](https://user-images.githubusercontent.com/3921442/140025590-22282a2e-fda6-40b0-a5ab-fcefb19f79ca.png)

`when use  theme Ziro scheme blue-light`

![image](https://user-images.githubusercontent.com/3921442/140026226-4899cbfa-0b45-42e3-acc1-d4e8e4ac6593.png)

**Comment by JulienMaille** [comment]
I can't reproduce that issue.
Can you delete .spicetify and spicetify-cli folders
Then reinstall Spicetify `curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh`

**Comment by azurefang** [comment]
> I can't reproduce that issue. Can you delete .spicetify and spicetify-cli folders Then reinstall Spicetify `curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh`

I reinstalled spicetify and It has not worked, then I deleted .config/spicetify/ and reinstalled this theme. That shell script said `error You haven't backed up and Spotify cannot be backed up at this state. Please re-install Spotify then run "spicetify backup apply"`, so I reinstalled spotify and ran this command. Now It's solved, lol.

Thank you for the support and this project.
